export type DrugEntry = {
  genericName: string
  brandNames: string
  drugClass: string
  indications: string
  dosage: string
  route: string
  sideEffects: string
  warnings: string
  interactions: string
  foodInteractions: string
  contraindications: string
  monitoring: string
  notes: string
  alsoUsedIn: string
}

export type DrugCategory =
  | 'All'
  | 'Antibiotic'
  | 'Antifungal'
  | 'Behavioral / Sedative'
  | 'Anticonvulsant'
  | 'NSAID / Pain'
  | 'Opioid / Analgesic'
  | 'Allergy / Dermatology'
  | 'Immunosuppressant'
  | 'Corticosteroid'
  | 'Cardiac'
  | 'GI'
  | 'Endocrine'
  | 'Antiparasitic'
  | 'Chemotherapy'
  | 'Ophthalmic'
  | 'Otic'
  | 'Emergency / Reversal'
  | 'Miscellaneous'

export const DRUG_CATEGORIES: DrugCategory[] = [
  'All','Antibiotic','Antifungal','Behavioral / Sedative','Anticonvulsant',
  'NSAID / Pain','Opioid / Analgesic','Allergy / Dermatology','Immunosuppressant',
  'Corticosteroid','Cardiac','GI','Endocrine','Antiparasitic','Chemotherapy',
  'Ophthalmic','Otic','Emergency / Reversal','Miscellaneous'
]

export function classifyDrug(drugClass: string): DrugCategory {
  const dc = drugClass.toLowerCase()
  if (/antibiotic|penicillin|cephalosporin|fluoroquinolone|tetracycline|lincosamide|macrolide|folate|amphenicol|rifamycin|aminoglycoside|nitroimidazole/.test(dc)) return 'Antibiotic'
  if (/antifungal|azole antifungal|triazole|allylamine|griseofulvin/.test(dc)) return 'Antifungal'
  if (/sari|phenothiazine|benzodiazepine|alpha-2|mao-b|azapirone|ssri|tricyclic/.test(dc)) return 'Behavioral / Sedative'
  if (/anticonvulsant|barbiturate|halide|pyrrolidone/.test(dc)) return 'Anticonvulsant'
  if (/nsaid|piprant|nmda|anti-ngf|muscle relaxant/.test(dc)) return 'NSAID / Pain'
  if (/opioid|mu-agonist|partial mu/.test(dc)) return 'Opioid / Analgesic'
  if (/jak|anti-il|antihistamine|rheological/.test(dc)) return 'Allergy / Dermatology'
  if (/purine|immunosuppressant/.test(dc)) return 'Immunosuppressant'
  if (/corticosteroid|glucocorticoid/.test(dc)) return 'Corticosteroid'
  if (/calcineurin/.test(dc) && !/ophthalmic/.test(dc)) return 'Allergy / Dermatology'
  if (/inodilator|ace inhibitor|loop diuretic|potassium-sparing|calcium channel|beta-blocker|cardiac glycoside|antiplatelet/.test(dc)) return 'Cardiac'
  if (/proton pump|h2 receptor|mucosal|nk1|dopamine antagonist|5-ht3|ghrelin|appetite|bile acid|osmotic laxative/.test(dc)) return 'GI'
  if (/thyroid|thioamide|hydroxysteroid|insulin/.test(dc)) return 'Endocrine'
  if (/anthelmintic|macrocyclic|isoxazoline|avermectin|organoarsenical|benzimidazole|isoquinolone|tetrahydropyrimidine|milbemycin/.test(dc)) return 'Antiparasitic'
  if (/alkylating|anthracycline|vinca|nitrosourea|tyrosine kinase/.test(dc)) return 'Chemotherapy'
  if (/ophthalmic|prostaglandin analog|carbonic anhydrase/.test(dc)) return 'Ophthalmic'
  if (/otic/.test(dc)) return 'Otic'
  if (/reversal|catecholamine|adsorbent|antioxidant|fat-soluble vitamin|benzodiazepine antagonist/.test(dc)) return 'Emergency / Reversal'
  return 'Miscellaneous'
}

export type SafetyFlags = {
  mdr1: boolean
  nsaidSteroid: boolean
  speciesContra: boolean
  boxedWarning: boolean
  highRisk: boolean
}

export function getSafetyFlags(drug: DrugEntry): SafetyFlags {
  const w = `${drug.warnings} ${drug.contraindications} ${drug.interactions}`.toLowerCase()
  return {
    mdr1: /mdr1|abcb1/.test(w),
    nsaidSteroid: /never combine|never with other nsaid/.test(w),
    speciesContra: /cats \(contraindicated|cats \(fatal|absolute|contraindicated in cats/.test(w),
    boxedWarning: /boxed warning|fda boxed/.test(w),
    highRisk: /narrow therapeutic|cumulative cardiotoxicity|cumulative hepatotoxicity/.test(w),
  }
}

export function hasAnySafetyFlag(flags: SafetyFlags): boolean {
  return Object.values(flags).some(Boolean)
}

// Simple fuzzy-ish search: checks if all query words appear in the combined text
export function matchesDrug(drug: DrugEntry, query: string): boolean {
  if (!query.trim()) return true
  const haystack = `${drug.genericName} ${drug.brandNames} ${drug.drugClass} ${drug.indications}`.toLowerCase()
  const words = query.toLowerCase().split(/\s+/).filter(Boolean)
  return words.every(w => haystack.includes(w))
}

export function slugifyDrug(drug: DrugEntry): string {
  return drug.genericName
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

export function findDrugBySlug(slug: string): DrugEntry | undefined {
  return DRUGS.find(d => slugifyDrug(d) === slug)
}

export const DRUGS: DrugEntry[] = [
  {genericName:"Amoxicillin",brandNames:"Amoxil; Amoxi-Tabs",drugClass:"Aminopenicillin antibiotic",indications:"Skin infections; UTIs; respiratory infections; wound infections",dosage:"10-25 mg/kg PO q8-12h",route:"Oral",sideEffects:"Vomiting; diarrhea; soft stool",warnings:"Allergic reactions (rare); anaphylaxis",interactions:"Bacteriostatic antibiotics (tetracyclines; chloramphenicol) may reduce efficacy; methotrexate levels increased; aminoglycosides synergy",foodInteractions:"Give with food to reduce GI upset",contraindications:"Penicillin allergy; caution in renal impairment",monitoring:"None routine; monitor for GI signs",notes:"Broad-spectrum; no beta-lactamase coverage",alsoUsedIn:"Cats; horses; small mammals"},
  {genericName:"Amoxicillin-Clavulanate",brandNames:"Clavamox; Augmentin",drugClass:"Beta-lactam + beta-lactamase inhibitor",indications:"Skin/soft tissue infections; UTIs; bite wounds; dental infections; pyoderma",dosage:"12.5-25 mg/kg PO q12h",route:"Oral",sideEffects:"Vomiting; diarrhea; decreased appetite",warnings:"Hepatotoxicity (rare); allergic reactions",interactions:"Same as amoxicillin; allopurinol may increase rash risk",foodInteractions:"Give with food",contraindications:"Penicillin allergy; severe hepatic disease",monitoring:"Liver values if prolonged use",notes:"Gold standard for empiric skin/bite wound therapy",alsoUsedIn:"Cats"},
  {genericName:"Cephalexin",brandNames:"Keflex; Rilexine",drugClass:"1st-gen cephalosporin",indications:"Pyoderma; skin infections; UTIs; bone infections; wound infections",dosage:"22-30 mg/kg PO q8-12h",route:"Oral",sideEffects:"Vomiting; diarrhea; drooling",warnings:"Rare nephrotoxicity; allergic cross-reactivity with penicillins",interactions:"Aminoglycosides (nephrotoxicity synergy); probenecid increases levels",foodInteractions:"Give with food if GI upset",contraindications:"Cephalosporin/penicillin allergy",monitoring:"None routine",notes:"First-line for canine pyoderma",alsoUsedIn:"Cats"},
  {genericName:"Cefpodoxime",brandNames:"Simplicef",drugClass:"3rd-gen cephalosporin",indications:"Skin infections; pyoderma; wound infections; UTIs",dosage:"5-10 mg/kg PO q24h",route:"Oral",sideEffects:"Vomiting; diarrhea; decreased appetite",warnings:"Rare allergic reactions",interactions:"Antacids may reduce absorption; probenecid increases levels",foodInteractions:"Give with food",contraindications:"Cephalosporin allergy",monitoring:"None routine",notes:"Once-daily dosing advantage; good compliance",alsoUsedIn:"Cats (off-label)"},
  {genericName:"Cefovecin",brandNames:"Convenia",drugClass:"3rd-gen cephalosporin (long-acting injectable)",indications:"Skin infections; UTIs; wound infections; abscesses",dosage:"8 mg/kg SC single injection; lasts 14 days",route:"Subcutaneous injection",sideEffects:"Vomiting; diarrhea; injection site reactions",warnings:"Cannot withdraw once given; allergic reactions; GI flora disruption",interactions:"Highly protein-bound; may displace other protein-bound drugs",foodInteractions:"N/A (injectable)",contraindications:"Cephalosporin allergy; severe renal impairment (prolonged duration)",monitoring:"Renal values in kidney disease",notes:"14-day single-dose; ideal for non-compliant patients",alsoUsedIn:"Cats"},
  {genericName:"Metronidazole",brandNames:"Flagyl",drugClass:"Nitroimidazole antibiotic/antiprotozoal",indications:"Giardia; anaerobic infections; IBD; colitis; periodontal disease; hepatic encephalopathy",dosage:"10-15 mg/kg PO q12h (infections); 7.5 mg/kg q12h (IBD)",route:"Oral; IV",sideEffects:"Nausea; vomiting; decreased appetite; metallic taste",warnings:"Neurotoxicity at high doses/prolonged use (ataxia; seizures; nystagmus); teratogenic",interactions:"Phenobarbital increases metabolism (reduced efficacy); warfarin potentiation; alcohol/ethanol products",foodInteractions:"Give with food",contraindications:"Pregnancy; liver disease (use reduced dose); seizure disorders at high doses; nursing",monitoring:"Neurologic signs if >2 weeks at high dose",notes:"Reversible neurotoxicity if caught early",alsoUsedIn:"Cats; horses; exotics"},
  {genericName:"Enrofloxacin",brandNames:"Baytril",drugClass:"Fluoroquinolone",indications:"UTIs; skin infections; respiratory infections; prostatitis; osteomyelitis",dosage:"5-20 mg/kg PO/IV q24h",route:"Oral; IV; IM",sideEffects:"GI upset; CNS stimulation (rare)",warnings:"Cartilage damage in growing dogs (<12-18 months); seizures at high doses; retinal toxicity in cats",interactions:"NSAIDs may increase seizure risk; antacids/sucralfate reduce absorption (give 2h apart); theophylline levels increased; cyclosporine levels increased",foodInteractions:"Give on empty stomach or with food; avoid dairy/antacids within 2h",contraindications:"Growing dogs (<12-18 months); epileptic dogs (lower threshold); NOT in cats at high doses (retinal degeneration)",monitoring:"None routine; avoid in young dogs",notes:"Concentration-dependent killing; give full daily dose at once",alsoUsedIn:"Cats (5 mg/kg max); exotic birds; reptiles"},
  {genericName:"Doxycycline",brandNames:"Vibramycin; Doxirobe",drugClass:"Tetracycline",indications:"Tick-borne diseases (Lyme; ehrlichiosis; anaplasmosis; RMSF); leptospirosis; respiratory infections; Wolbachia in heartworm",dosage:"5-10 mg/kg PO q12h; or 10 mg/kg q24h",route:"Oral; IV",sideEffects:"Esophageal stricture if pill lodges; GI upset; photosensitivity",warnings:"Esophageal ulceration (give with food + water); tooth discoloration in young; hepatotoxicity (rare)",interactions:"Antacids/calcium/iron reduce absorption; phenobarbital increases metabolism; warfarin potentiation; digoxin levels increased",foodInteractions:"MUST give with food and water to prevent esophageal damage; avoid dairy within 2h",contraindications:"Pregnancy (tooth/bone); severe hepatic disease",monitoring:"None routine; hepatic if prolonged",notes:"First-line for tick-borne diseases; less renal impact than other tetracyclines",alsoUsedIn:"Cats; horses; birds; reptiles"},
  {genericName:"Clindamycin",brandNames:"Antirobe; Cleocin",drugClass:"Lincosamide",indications:"Deep pyoderma; bone infections; dental infections; toxoplasmosis; soft tissue infections; MRSP",dosage:"5.5-11 mg/kg PO q12h",route:"Oral; IV; IM",sideEffects:"Vomiting; diarrhea; esophagitis",warnings:"Pseudomembranous colitis (rare); hepatotoxicity (rare); esophageal stricture",interactions:"Neuromuscular blockers (enhanced); erythromycin (antagonism); kaolin-pectin reduces absorption",foodInteractions:"Give with food",contraindications:"Clindamycin/lincomycin allergy",monitoring:"None routine",notes:"Good bone and abscess penetration",alsoUsedIn:"Cats"},
  {genericName:"Azithromycin",brandNames:"Zithromax",drugClass:"Macrolide",indications:"Upper respiratory; Bartonella; Mycobacterium; babesiosis adjunct; papillomatosis",dosage:"5-10 mg/kg PO q24h or q48h",route:"Oral; IV",sideEffects:"Vomiting; diarrhea; decreased appetite",warnings:"QT prolongation (rare); hepatotoxicity",interactions:"Antacids reduce absorption; cyclosporine levels increased; digoxin levels increased",foodInteractions:"Give on empty stomach or with food",contraindications:"Macrolide allergy; hepatic impairment",monitoring:"None routine",notes:"Long tissue half-life; pulse dosing common",alsoUsedIn:"Cats; birds; reptiles"},
  {genericName:"Trimethoprim-Sulfonamide",brandNames:"Tribrissen; Bactrim; Septra",drugClass:"Folate inhibitor combo",indications:"UTIs; prostatitis; skin infections; Nocardia; coccidiosis; toxoplasmosis",dosage:"15-30 mg/kg PO q12h",route:"Oral; IV",sideEffects:"Vomiting; diarrhea; decreased appetite",warnings:"KCS (dry eye); bone marrow suppression; hepatotoxicity; immune-mediated reactions; hypothyroidism (prolonged use)",interactions:"Potentiates warfarin; phenytoin; methotrexate; digoxin; potassium-sparing diuretics increase hyperkalemia risk",foodInteractions:"Give with food",contraindications:"Hepatic disease; bone marrow disorders; pregnancy; Dobermans (increased idiosyncratic reactions)",monitoring:"Schirmer tear test q2-4wks; CBC if >14 days; thyroid if chronic",notes:"Dobermans at higher risk for sulfonamide reactions",alsoUsedIn:"Cats; horses"},
  {genericName:"Chloramphenicol",brandNames:"Chloromycetin",drugClass:"Amphenicol",indications:"MRSA/MRSP; CNS infections; rickettsia; anaerobes when other options unavailable",dosage:"40-50 mg/kg PO q8h",route:"Oral; IV; topical ophthalmic",sideEffects:"GI upset; bone marrow suppression (dose-dependent)",warnings:"IRREVERSIBLE aplastic anemia in HUMANS handling drug (wear gloves); dose-dependent myelosuppression in dogs",interactions:"Phenobarbital (increased metabolism); inhibits CYP enzymes (increases cyclosporine; phenobarbital; cisapride)",foodInteractions:"Give on empty stomach for best absorption; with food if GI upset",contraindications:"Bone marrow disorders; HUMAN handlers who are pregnant or immunocompromised MUST NOT handle",monitoring:"CBC weekly during treatment",notes:"Humans handling must wear gloves; inform owners of human aplastic anemia risk",alsoUsedIn:"Cats; horses; birds; reptiles"},
  {genericName:"Rifampin",brandNames:"Rifadin",drugClass:"Rifamycin",indications:"Mycobacterial infections; MRSA/MRSP (adjunct only); deep staphylococcal infections",dosage:"5-10 mg/kg PO q12-24h",route:"Oral",sideEffects:"Orange/red discoloration of urine/tears/saliva; GI upset; hepatotoxicity",warnings:"Hepatotoxicity; powerful CYP inducer",interactions:"POTENT CYP inducer: decreases levels of cyclosporine; ketoconazole; itraconazole; corticosteroids; digoxin; theophylline; many others; NEVER use as monotherapy (rapid resistance)",foodInteractions:"Give on empty stomach",contraindications:"Hepatic disease; NEVER as monotherapy",monitoring:"Liver values q2wks",notes:"ALWAYS combine with another antibiotic to prevent resistance",alsoUsedIn:"Cats; horses"},
  {genericName:"Gentamicin",brandNames:"Gentocin",drugClass:"Aminoglycoside",indications:"Severe gram-negative infections (E. coli; Pseudomonas); sepsis; pyelonephritis",dosage:"6-10 mg/kg IV/IM/SC q24h",route:"IV; IM; SC; topical (otic/ophthalmic)",sideEffects:"Nephrotoxicity; ototoxicity; injection site pain",warnings:"Nephrotoxicity (dose-limiting); vestibular/auditory toxicity (irreversible); neuromuscular blockade",interactions:"Furosemide (increased ototoxicity); cisplatin (increased nephrotoxicity); NSAIDs (increased nephrotoxicity); neuromuscular blockers (potentiated)",foodInteractions:"N/A (injectable); ensure hydration",contraindications:"Renal disease; dehydration; concurrent nephrotoxins",monitoring:"BUN/creatinine q48-72h during treatment; urinalysis; peak/trough levels if available",notes:"Once-daily dosing reduces toxicity; ensure adequate hydration",alsoUsedIn:"Cats (use with extreme caution); horses"},
  {genericName:"Ketoconazole",brandNames:"Nizoral",drugClass:"Azole antifungal",indications:"Blastomycosis; histoplasmosis; coccidioidomycosis; Malassezia dermatitis; hyperadrenocorticism (off-label)",dosage:"5-10 mg/kg PO q12h (systemic); 10 mg/kg q24h (Malassezia)",route:"Oral; topical",sideEffects:"Hepatotoxicity; GI upset; decreased appetite; lightened coat color",warnings:"Hepatotoxicity (dose-dependent); teratogenic; adrenal suppression",interactions:"POTENT CYP inhibitor: increases cyclosporine; ivermectin; midazolam; sildenafil; cisapride; many others; antacids/H2-blockers reduce absorption",foodInteractions:"Give with food (needs acid for absorption); avoid antacids",contraindications:"Hepatic disease; pregnancy; concurrent hepatotoxic drugs",monitoring:"Liver values at 2wks then monthly",notes:"Intentionally used with cyclosporine to reduce cyclosporine dose (cost-saving)",alsoUsedIn:"Cats"},
  {genericName:"Fluconazole",brandNames:"Diflucan",drugClass:"Triazole antifungal",indications:"Cryptococcosis; CNS fungal infections; blastomycosis; coccidioidomycosis; dermatophytosis; Malassezia",dosage:"5-10 mg/kg PO q12-24h",route:"Oral; IV",sideEffects:"GI upset; hepatotoxicity (less than ketoconazole)",warnings:"Hepatotoxicity; teratogenic",interactions:"CYP inhibitor (less potent than ketoconazole): increases cyclosporine; phenytoin; warfarin levels",foodInteractions:"Give with or without food (acid-independent absorption)",contraindications:"Pregnancy; hepatic disease",monitoring:"Liver values monthly",notes:"Best CNS penetration of azoles; good urinary concentrations",alsoUsedIn:"Cats; horses; birds; reptiles"},
  {genericName:"Itraconazole",brandNames:"Sporanox; Itrafungol",drugClass:"Triazole antifungal",indications:"Blastomycosis; histoplasmosis; aspergillosis; dermatophytosis; sporotrichosis",dosage:"5 mg/kg PO q12-24h",route:"Oral",sideEffects:"GI upset; hepatotoxicity; vasculitis (rare)",warnings:"Hepatotoxicity; negative inotropic effect (heart failure risk); teratogenic",interactions:"CYP3A4 inhibitor: increases cyclosporine; digoxin; midazolam; vincristine; cisapride levels; antacids/H2-blockers reduce capsule absorption",foodInteractions:"Give capsules with food (needs acid); solution on empty stomach",contraindications:"Congestive heart failure; pregnancy; hepatic disease",monitoring:"Liver values monthly; levels if available",notes:"Pulse therapy option for dermatophytosis (1wk on/1wk off)",alsoUsedIn:"Cats"},
  {genericName:"Terbinafine",brandNames:"Lamisil",drugClass:"Allylamine antifungal",indications:"Dermatophytosis (ringworm); some systemic mycoses adjunct",dosage:"20-30 mg/kg PO q24h",route:"Oral",sideEffects:"GI upset; hepatotoxicity (rare); decreased appetite",warnings:"Hepatotoxicity (rare); neutropenia (rare)",interactions:"Cimetidine increases levels; rifampin decreases levels; cyclosporine levels decreased",foodInteractions:"Give with food",contraindications:"Hepatic disease",monitoring:"Liver values if prolonged use",notes:"Often combined with itraconazole for stubborn dermatophytosis",alsoUsedIn:"Cats"},
  {genericName:"Griseofulvin",brandNames:"Fulvicin",drugClass:"Antifungal (griseofulvin class)",indications:"Dermatophytosis (ringworm)",dosage:"25-50 mg/kg PO q12-24h (microsize); 5-10 mg/kg (ultramicrosize)",route:"Oral",sideEffects:"GI upset; hepatotoxicity; photosensitivity; bone marrow suppression",warnings:"Teratogenic (ABSOLUTE); bone marrow suppression; hepatotoxicity",interactions:"Phenobarbital decreases efficacy; warfarin effect decreased; cyclosporine decreased",foodInteractions:"Give with fatty meal (increases absorption)",contraindications:"Pregnancy (ABSOLUTE teratogen); FIV+ cats; bone marrow disease; hepatic disease; handlers must not be pregnant",monitoring:"CBC/liver monthly",notes:"Largely replaced by itraconazole/terbinafine due to toxicity",alsoUsedIn:"Cats (NOT FIV+); horses"},
  {genericName:"Trazodone",brandNames:"Desyrel; Oleptro",drugClass:"SARI (serotonin antagonist/reuptake inhibitor)",indications:"Anxiety; storm/noise phobia; post-surgical confinement; separation anxiety; vet visit anxiety",dosage:"3-10 mg/kg PO q8-24h (event); 2-5 mg/kg (daily)",route:"Oral",sideEffects:"Sedation; GI upset; ataxia; priapism (rare)",warnings:"Serotonin syndrome (with SSRIs/MAOIs/tramadol); cardiac arrhythmias (rare)",interactions:"SSRIs/SNRIs (serotonin syndrome risk); MAOIs (CONTRAINDICATED); tramadol; buspirone; CNS depressants (enhanced sedation)",foodInteractions:"Give with food",contraindications:"MAOI use within 14 days; severe cardiac disease",monitoring:"None routine",notes:"Commonly combined with gabapentin for vet visits; onset 1-2h",alsoUsedIn:"Cats (off-label)"},
  {genericName:"Acepromazine",brandNames:"PromAce; Atravet",drugClass:"Phenothiazine tranquilizer",indications:"Pre-anesthetic sedation; anxiety; travel; chemical restraint",dosage:"0.025-0.1 mg/kg IV/IM/SC; 0.5-2.2 mg/kg PO",route:"Oral; IV; IM; SC",sideEffects:"Hypotension; bradycardia; third eyelid protrusion; paradoxical excitement (terriers)",warnings:"Severe hypotension; seizure threshold lowering; NO reversal agent; prolonged sedation in MDR1 dogs",interactions:"Organophosphates (potentiated); CNS depressants; antihypertensives; epinephrine (paradoxical hypotension)",foodInteractions:"Give with food (oral)",contraindications:"Seizure history; boxers/brachycephalics (severe hypotension); dehydration/shock/hypovolemia; MDR1/ABCB1 mutation (prolonged profound sedation); aggressive dogs (may disinhibit)",monitoring:"Blood pressure in sensitive breeds",notes:"MDR1 dogs: use 25-50% dose or avoid; does NOT provide analgesia",alsoUsedIn:"Cats; horses"},
  {genericName:"Gabapentin",brandNames:"Neurontin",drugClass:"Gabapentinoid anticonvulsant/analgesic",indications:"Neuropathic pain; seizures (adjunct); anxiety; pre-visit sedation",dosage:"5-10 mg/kg PO q8-12h (pain/anxiety); 10-20 mg/kg (seizures)",route:"Oral",sideEffects:"Sedation; ataxia; weight gain",warnings:"Rebound seizures if stopped abruptly (when used as anticonvulsant)",interactions:"CNS depressants (enhanced sedation); antacids reduce absorption (give 2h apart)",foodInteractions:"Give with or without food; avoid liquid formulation with xylitol",contraindications:"Xylitol-containing liquid formulations (TOXIC); adjust dose in renal impairment",monitoring:"None routine; renal values in kidney disease",notes:"Liquid forms may contain xylitol; CHECK LABEL; onset ~1-2h",alsoUsedIn:"Cats"},
  {genericName:"Fluoxetine",brandNames:"Reconcile; Prozac",drugClass:"SSRI",indications:"Separation anxiety; compulsive disorders; aggression; anxiety; thunderstorm phobia",dosage:"1-2 mg/kg PO q24h",route:"Oral",sideEffects:"Decreased appetite; lethargy; GI upset; restlessness",warnings:"Serotonin syndrome; seizures (rare); behavioral changes in first 2-4 wks",interactions:"MAOIs (CONTRAINDICATED; wait 5wks washout); tramadol; trazodone; buspirone (serotonin syndrome); NSAIDs (increased bleeding)",foodInteractions:"Give with or without food",contraindications:"MAOI use within 14 days; seizure disorders (relative)",monitoring:"Behavior log; takes 4-8 weeks for full effect",notes:"Reconcile is FDA-approved for canine separation anxiety; must combine with behavior modification",alsoUsedIn:"Cats (off-label)"},
  {genericName:"Clomipramine",brandNames:"Clomicalm",drugClass:"Tricyclic antidepressant",indications:"Separation anxiety; compulsive disorders; anxiety",dosage:"1-3 mg/kg PO q12h",route:"Oral",sideEffects:"Sedation; dry mouth; GI upset; urinary retention; elevated liver enzymes",warnings:"Cardiac arrhythmias; seizure threshold lowering; serotonin syndrome with SSRIs",interactions:"MAOIs (CONTRAINDICATED); SSRIs; CNS depressants; cimetidine (increases levels); anticholinergics",foodInteractions:"Give with food",contraindications:"Cardiac arrhythmias; MAOI use; urinary retention; glaucoma; seizure disorders",monitoring:"Liver values; ECG if cardiac concern",notes:"FDA-approved for canine separation anxiety (Clomicalm); 2-4wk onset",alsoUsedIn:"Cats (off-label)"},
  {genericName:"Alprazolam",brandNames:"Xanax",drugClass:"Benzodiazepine",indications:"Noise phobia; storm anxiety; situational anxiety; panic",dosage:"0.01-0.1 mg/kg PO q4-12h PRN",route:"Oral",sideEffects:"Sedation; ataxia; paradoxical excitement; increased appetite",warnings:"Hepatic failure in cats (oral diazepam); physical dependence; rebound anxiety",interactions:"CNS depressants; ketoconazole/itraconazole (increase levels); rifampin (decreases levels)",foodInteractions:"Give with or without food",contraindications:"Hepatic disease; aggressive animals (may disinhibit); glaucoma",monitoring:"None routine",notes:"Rapid onset (30-60min); short duration; tolerance develops",alsoUsedIn:"Cats (use with caution)"},
  {genericName:"Diazepam",brandNames:"Valium",drugClass:"Benzodiazepine",indications:"Status epilepticus (IV); appetite stimulation (cats); muscle relaxation; anxiety",dosage:"0.5-2 mg/kg IV (seizures); 0.2-0.5 mg/kg PO q8-12h (anxiety/muscle)",route:"IV; rectal; oral",sideEffects:"Sedation; ataxia; paradoxical excitement",warnings:"Status epilepticus if stopped abruptly after chronic use; hepatic necrosis in cats (oral)",interactions:"CNS depressants; cimetidine (increases levels); rifampin (decreases); erythromycin (increases)",foodInteractions:"Give with food (oral)",contraindications:"ORAL DIAZEPAM CONTRAINDICATED IN CATS (hepatic necrosis); hepatic disease",monitoring:"None routine",notes:"IV or rectal for acute seizures; store away from plastic (absorbs)",alsoUsedIn:"Cats (IV only; NEVER oral)"},
  {genericName:"Dexmedetomidine",brandNames:"Sileo (oromucosal gel); Dexdomitor (injectable)",drugClass:"Alpha-2 adrenergic agonist",indications:"Noise aversion (Sileo); sedation; pre-anesthesia; chemical restraint",dosage:"Sileo gel: 125 mcg/m2 oromucosal q2h PRN; Injectable: 5-40 mcg/kg IV/IM",route:"Oromucosal; IV; IM",sideEffects:"Bradycardia; hypothermia; vomiting; pale gums; initial hypertension then hypotension",warnings:"Severe bradycardia; AV block; profound sedation; peripheral vasoconstriction",interactions:"Other sedatives/anesthetics (profound sedation); opioids (enhanced effects); anticholinergics (cardiac arrhythmias)",foodInteractions:"N/A (gel/injectable)",contraindications:"Severe cardiac/respiratory/hepatic/renal disease; shock; debilitated/geriatric animals; very young",monitoring:"Heart rate; blood pressure; temperature; SpO2",notes:"Sileo gel: FDA-approved for canine noise aversion; fully reversible with atipamezole",alsoUsedIn:"Cats (injectable)"},
  {genericName:"Selegiline",brandNames:"Anipryl",drugClass:"MAO-B inhibitor",indications:"Canine cognitive dysfunction syndrome (CDS); pituitary-dependent hyperadrenocorticism",dosage:"0.5-1 mg/kg PO q24h (morning)",route:"Oral",sideEffects:"Restlessness; GI upset; disorientation; stereotypic behavior",warnings:"Serotonin syndrome; hypertensive crisis with contraindicated drugs",interactions:"SSRIs; TCAs; tramadol; meperidine (ALL CONTRAINDICATED: serotonin syndrome/hypertensive crisis); amitraz (Preventic collars)",foodInteractions:"Give in morning (may cause restlessness)",contraindications:"Concurrent SSRI/TCA/tramadol/meperidine use; amitraz products",monitoring:"Behavior log; takes 4-8wks for CDS benefit",notes:"FDA-approved for canine CDS; at high doses may inhibit MAO-A too",alsoUsedIn:"Not commonly used in cats"},
  {genericName:"Buspirone",brandNames:"BuSpar",drugClass:"Azapirone anxiolytic",indications:"Mild anxiety; urine marking (cats); generalized anxiety (dogs)",dosage:"0.5-2 mg/kg PO q8-12h",route:"Oral",sideEffects:"Restlessness; GI upset; increased friendliness/affection",warnings:"Serotonin syndrome (rare; with serotonergic drugs)",interactions:"SSRIs (serotonin risk); MAOIs (CONTRAINDICATED); erythromycin/ketoconazole (increase levels)",foodInteractions:"Give with or without food",contraindications:"MAOI use",monitoring:"None routine",notes:"Non-sedating; 2-4wk onset; more effective in cats than dogs",alsoUsedIn:"Cats (urine marking)"},
  {genericName:"Phenobarbital",brandNames:"Luminal; Solfoton",drugClass:"Barbiturate anticonvulsant",indications:"Epilepsy; seizure disorders",dosage:"2.5-5 mg/kg PO q12h (titrate to serum levels)",route:"Oral; IV; IM",sideEffects:"Sedation; ataxia; PU/PD/PP; hepatotoxicity; weight gain",warnings:"Hepatotoxicity (long-term); bone marrow suppression (rare); withdrawal seizures if stopped abruptly",interactions:"Potent CYP inducer: decreases levels of corticosteroids; cyclosporine; metronidazole; doxycycline; theophylline; many others; chloramphenicol increases phenobarbital levels",foodInteractions:"Give with food",contraindications:"Severe hepatic disease; severe anemia",monitoring:"Serum levels q2wks until stable then q6-12mo (target 20-35 mcg/mL); liver values + bile acids q6mo; CBC annually",notes:"Gold standard first-line anticonvulsant in dogs",alsoUsedIn:"Cats (use with caution; hepatotoxicity)"},
  {genericName:"Potassium Bromide",brandNames:"KBr",drugClass:"Halide anticonvulsant",indications:"Epilepsy (adjunct with phenobarbital or monotherapy)",dosage:"20-40 mg/kg PO q24h (loading: 400-600 mg/kg divided over 5 days)",route:"Oral",sideEffects:"Sedation; ataxia; PU/PD; vomiting; pancreatitis; skin rash",warnings:"Pancreatitis; bromism (toxicity); very long half-life (25 days); takes months to reach steady state",interactions:"Furosemide/IV saline (increases bromide excretion; may precipitate seizures); chloride-containing foods alter levels",foodInteractions:"Give with food to reduce GI upset; CONSISTENT dietary chloride is critical",contraindications:"CATS (CONTRAINDICATED: fatal eosinophilic bronchitis); renal disease",monitoring:"Serum bromide levels q3-6mo (target 1000-3000 mg/L; 2000-2500 if adjunct); renal values",notes:"NEVER use in cats; dietary salt changes affect levels dramatically",alsoUsedIn:"Dogs only"},
  {genericName:"Levetiracetam",brandNames:"Keppra",drugClass:"Pyrrolidone anticonvulsant",indications:"Epilepsy (adjunct or monotherapy); status epilepticus; cluster seizures",dosage:"20-60 mg/kg PO q8h (regular); 30-40 mg/kg PO q12h (extended-release)",route:"Oral; IV",sideEffects:"Sedation; ataxia; behavioral changes; GI upset",warnings:"Few serious; mild sedation usually transient",interactions:"Phenobarbital increases levetiracetam clearance (need higher doses); few other significant interactions",foodInteractions:"Give with or without food; do not crush extended-release",contraindications:"Few true contraindications; dose adjust in renal impairment",monitoring:"Serum levels if available (12-46 mcg/mL); renal values",notes:"Very safe profile; good add-on to phenobarbital; IV for emergency",alsoUsedIn:"Cats"},
  {genericName:"Zonisamide",brandNames:"Zonegran",drugClass:"Sulfonamide-derivative anticonvulsant",indications:"Epilepsy (adjunct or monotherapy)",dosage:"5-10 mg/kg PO q12h",route:"Oral",sideEffects:"Sedation; ataxia; decreased appetite; GI upset; hepatotoxicity",warnings:"Hepatotoxicity; renal tubular acidosis; KCS (dry eye); hyperthermia; idiosyncratic reactions",interactions:"Phenobarbital increases clearance; CYP inhibitors increase levels",foodInteractions:"Give with food",contraindications:"Sulfonamide allergy; hepatic disease; renal disease",monitoring:"Serum levels (10-40 mcg/mL); liver/renal values; Schirmer tear test q3-6mo",notes:"Cross-sensitivity in sulfonamide-allergic patients possible",alsoUsedIn:"Cats"},
  {genericName:"Carprofen",brandNames:"Rimadyl; Novox",drugClass:"NSAID (COX-2 preferential)",indications:"Osteoarthritis; postoperative pain; musculoskeletal pain; inflammation",dosage:"4.4 mg/kg PO q24h or 2.2 mg/kg q12h",route:"Oral; SC (injectable)",sideEffects:"GI upset; vomiting; diarrhea; decreased appetite",warnings:"Hepatotoxicity (idiosyncratic especially Labradors); GI ulceration/perforation; renal failure; NEVER with other NSAIDs or corticosteroids",interactions:"Other NSAIDs (NEVER combine); corticosteroids (NEVER combine; 5-7 day washout); ACE inhibitors + diuretics (renal risk); aspirin; anticoagulants",foodInteractions:"Give with food",contraindications:"GI ulceration; bleeding disorders; renal/hepatic disease; dehydration; <6 weeks age; concurrent NSAID/steroid use",monitoring:"Liver values at 2wks then q3-6mo; BUN/creatinine; PCV",notes:"5-7 day washout between NSAIDs or NSAID-steroid switches",alsoUsedIn:"Dogs only (cat formulation exists outside US)"},
  {genericName:"Meloxicam",brandNames:"Metacam",drugClass:"NSAID (COX-2 preferential)",indications:"Osteoarthritis; postoperative pain; musculoskeletal inflammation",dosage:"0.1 mg/kg PO q24h (after 0.2 mg/kg loading dose day 1)",route:"Oral suspension; SC (injectable)",sideEffects:"GI upset; vomiting; diarrhea; decreased appetite; soft stool",warnings:"GI ulceration; renal failure; hepatotoxicity; NEVER with other NSAIDs/steroids; NOT for repeated use in cats (US label)",interactions:"Same as carprofen",foodInteractions:"Give with food",contraindications:"Same as carprofen",monitoring:"Same as carprofen",notes:"Liquid suspension allows precise small-dog dosing",alsoUsedIn:"Cats (single SC dose only per US label)"},
  {genericName:"Deracoxib",brandNames:"Deramaxx",drugClass:"NSAID (COX-2 selective)",indications:"Osteoarthritis; postoperative orthopedic/dental pain",dosage:"1-2 mg/kg PO q24h (OA); 3-4 mg/kg PO q24h x7d (post-op)",route:"Oral chewable",sideEffects:"GI upset; bloody/black stool; decreased appetite",warnings:"GI ulceration/perforation (especially at higher surgical doses); renal failure; hepatotoxicity",interactions:"Same NSAID class interactions as carprofen",foodInteractions:"Give with food",contraindications:"Same as carprofen",monitoring:"Same as carprofen",notes:"Higher post-surgical dose limited to 7 days",alsoUsedIn:"Dogs only"},
  {genericName:"Firocoxib",brandNames:"Previcox",drugClass:"NSAID (COX-2 selective)",indications:"Osteoarthritis; postoperative pain",dosage:"5 mg/kg PO q24h",route:"Oral chewable",sideEffects:"GI upset; vomiting; diarrhea; decreased appetite",warnings:"GI ulceration; renal toxicity; hepatotoxicity",interactions:"Same NSAID class interactions",foodInteractions:"Give with food",contraindications:"Same as carprofen; also not for dogs <10 weeks or <12.5 lbs",monitoring:"Same as carprofen",notes:"FDA-approved for both OA and post-op pain in dogs",alsoUsedIn:"Dogs; horses"},
  {genericName:"Grapiprant",brandNames:"Galliprant",drugClass:"Piprant (EP4 prostaglandin receptor antagonist)",indications:"Osteoarthritis pain; mild-moderate OA",dosage:"2 mg/kg PO q24h",route:"Oral",sideEffects:"Vomiting; diarrhea; soft stool; decreased appetite",warnings:"GI upset (milder than traditional NSAIDs); renal effects less studied",interactions:"Other NSAIDs (avoid); corticosteroids (avoid combination); highly protein-bound drugs",foodInteractions:"Give on empty stomach or with light food; food decreases absorption ~60%",contraindications:"<9 months; <3.6 kg; breeding/pregnant/lactating; GI ulceration",monitoring:"Liver/renal values periodically",notes:"Novel MOA; not a traditional NSAID; may be safer for GI/renal but less data",alsoUsedIn:"Dogs only"},
  {genericName:"Tramadol",brandNames:"Ultram",drugClass:"Opioid-like analgesic (weak mu-agonist + serotonin/NE reuptake inhibitor)",indications:"Mild-moderate pain; chronic pain adjunct; multimodal analgesia",dosage:"2-5 mg/kg PO q8-12h",route:"Oral",sideEffects:"Sedation; GI upset; constipation; dysphoria; panting",warnings:"Seizures; serotonin syndrome (with SSRIs/MAOIs/TCAs); respiratory depression (high doses)",interactions:"SSRIs; MAOIs (CONTRAINDICATED); TCAs; trazodone (serotonin syndrome); carbamazepine (reduces effect); quinidine (increases effect)",foodInteractions:"Give with food if GI upset",contraindications:"MAOI use; seizure disorders; concurrent serotonergic drugs",monitoring:"None routine",notes:"Dogs poorly convert to active metabolite (O-desmethyltramadol); efficacy debated in dogs vs humans",alsoUsedIn:"Cats (better efficacy than dogs)"},
  {genericName:"Buprenorphine",brandNames:"Simbadol; Buprenex",drugClass:"Partial mu-opioid agonist",indications:"Moderate pain; perioperative analgesia; oral transmucosal in cats",dosage:"0.01-0.03 mg/kg IV/IM q6-12h; OTM in cats: 0.02-0.03 mg/kg",route:"IV; IM; OTM (cats); transdermal (Simbadol cats)",sideEffects:"Sedation; mild respiratory depression; dysphoria; bradycardia",warnings:"Respiratory depression (less than full agonists); ceiling effect limits dose escalation",interactions:"Other opioids (may reduce efficacy of full agonists due to partial agonism); CNS depressants",foodInteractions:"N/A (injectable/OTM)",contraindications:"None absolute; dose reduce in hepatic disease",monitoring:"Heart rate; respiratory rate; pain scoring",notes:"Partial agonist; ceiling on respiratory depression; OTM route in cats very effective",alsoUsedIn:"Cats (primary species)"},
  {genericName:"Amantadine",brandNames:"Symmetrel",drugClass:"NMDA receptor antagonist",indications:"Chronic pain adjunct; neuropathic pain; central sensitization; allodynia",dosage:"3-5 mg/kg PO q24h",route:"Oral",sideEffects:"GI upset; agitation; diarrhea",warnings:"CNS stimulation at high doses; rarely serotonin syndrome",interactions:"Trimethoprim-sulfa (increases levels); anticholinergics; serotonergic drugs (rare serotonin risk)",foodInteractions:"Give with food",contraindications:"Severe renal impairment (renally excreted); seizure history",monitoring:"None routine",notes:"Adjunct for NSAID-refractory chronic OA pain; wind-up pain",alsoUsedIn:"Cats (off-label)"},
  {genericName:"Bedinvetmab",brandNames:"Librela",drugClass:"Anti-NGF monoclonal antibody",indications:"Osteoarthritis pain",dosage:"0.5-1 mg/kg SC once monthly",route:"Subcutaneous injection",sideEffects:"Injection site reactions; UTI increase (reported); joint disorders",warnings:"Not for breeding/pregnant/lactating; minimal systemic metabolism",interactions:"Minimal drug interactions expected (biologic clearance)",foodInteractions:"N/A (injectable)",contraindications:"<12 months; not for breeding animals",monitoring:"None routine; pain scoring",notes:"First canine anti-NGF mAb for OA pain; monthly injection",alsoUsedIn:"Dogs only (frunevetmab/Solensia is the cat version)"},
  {genericName:"Methocarbamol",brandNames:"Robaxin",drugClass:"Centrally-acting muscle relaxant",indications:"Muscle spasms; IVDD adjunct; tetanus; tremorgenic mycotoxin ingestion; strychnine",dosage:"22-44 mg/kg PO q8h; up to 220 mg/kg/day IV (toxin tremors)",route:"Oral; IV",sideEffects:"Sedation; weakness; GI upset; drooling; darkened urine",warnings:"Respiratory depression (IV too fast); excessive sedation",interactions:"CNS depressants (enhanced sedation)",foodInteractions:"Give with food",contraindications:"Severe renal disease (metabolite accumulation); myasthenia gravis",monitoring:"None routine",notes:"IV for acute tremor/spasm emergencies",alsoUsedIn:"Cats; horses"},
  {genericName:"Oclacitinib",brandNames:"Apoquel",drugClass:"JAK inhibitor (JAK1/JAK3)",indications:"Allergic/atopic dermatitis (pruritus); allergic skin disease",dosage:"0.4-0.6 mg/kg PO q12h x14d then q24h",route:"Oral",sideEffects:"Vomiting; diarrhea; decreased appetite; lethargy; susceptibility to infections",warnings:"Demodicosis; papillomas; increased infection risk; potential tumor promotion (long-term); mast cell tumors (theoretical)",interactions:"Immunosuppressants (avoid combining); vaccines (may reduce response); CYP substrates (minor)",foodInteractions:"Give with or without food",contraindications:"<12 months; serious infections; Demodex; neoplasia history (relative)",monitoring:"CBC/chemistry at baseline and q6-12mo",notes:"NOT for use in dogs <12 months; do not exceed 16 weeks at q12h per label",alsoUsedIn:"Dogs only"},
  {genericName:"Lokivetmab",brandNames:"Cytopoint",drugClass:"Anti-IL-31 monoclonal antibody",indications:"Allergic/atopic dermatitis (pruritus)",dosage:"1-2 mg/kg SC q4-8wks",route:"Subcutaneous injection",sideEffects:"Injection site reactions (rare); lethargy (transient)",warnings:"Rare anaphylaxis",interactions:"Minimal interactions (biologic)",foodInteractions:"N/A (injectable)",contraindications:"Few; hypersensitivity to product",monitoring:"None routine",notes:"Injection by vet; minimal systemic immunosuppression; safe with most drugs",alsoUsedIn:"Dogs only"},
  {genericName:"Ilunocitinib",brandNames:"Zenrelia",drugClass:"JAK1 selective inhibitor",indications:"Allergic/atopic dermatitis (pruritus)",dosage:"Dose varies by weight bracket; per label",route:"Oral",sideEffects:"Vomiting; diarrhea; decreased appetite; UTIs",warnings:"Increased infection susceptibility; potential neoplasia risk (class); limited long-term data",interactions:"Immunosuppressants (avoid combining); CYP substrates",foodInteractions:"Give with or without food",contraindications:"<12 months; serious infections; neoplasia",monitoring:"CBC/chemistry at baseline and periodically",notes:"JAK1-selective (more targeted than oclacitinib); approved Sept 2024",alsoUsedIn:"Dogs only"},
  {genericName:"Cyclosporine",brandNames:"Atopica; Optimmune (ophthalmic)",drugClass:"Calcineurin inhibitor immunosuppressant",indications:"Atopic dermatitis; perianal fistulas; immune-mediated disease; KCS (ophthalmic)",dosage:"5 mg/kg PO q24h (atopy); can reduce to q48h once controlled",route:"Oral; ophthalmic",sideEffects:"Vomiting; diarrhea; gingival hyperplasia; papillomatosis; hirsutism; hypertrichosis",warnings:"Immunosuppression (increased infection/neoplasia risk); nephrotoxicity (less in dogs than humans); GI upset",interactions:"Ketoconazole/fluconazole (intentionally increases levels 2-3x for dose-sparing); azithromycin/erythromycin (increase levels); grapefruit juice; phenobarbital/rifampin (decrease levels); NSAIDs (renal risk)",foodInteractions:"Give on empty stomach (food reduces absorption); or freeze capsules to reduce nausea",contraindications:"Neoplasia history; serious infections; <6 months; breeding",monitoring:"Renal values periodically; monitor for papillomas/infections",notes:"Ketoconazole co-administration is a recognized dose-reduction strategy",alsoUsedIn:"Cats; horses"},
  {genericName:"Prednisone",brandNames:"Deltasone",drugClass:"Corticosteroid (glucocorticoid)",indications:"Allergic conditions; immune-mediated disease (IMHA; ITP; IMPA); IBD; CNS inflammation; Addison's; asthma; dermatitis",dosage:"Anti-inflammatory: 0.5-1 mg/kg PO q12-24h; Immunosuppressive: 2-4 mg/kg PO q12-24h; taper down",route:"Oral",sideEffects:"PU/PD; polyphagia; weight gain; panting; muscle wasting; behavior changes; GI ulceration",warnings:"Iatrogenic Cushing's; diabetes; immunosuppression; GI ulceration/perforation; pancreatitis; calcinosis cutis",interactions:"NSAIDs (NEVER combine; GI ulceration/hemorrhage); phenobarbital (increased metabolism); insulin (antagonized); diuretics (hypokalemia); vaccines (reduced response)",foodInteractions:"Give with food",contraindications:"GI ulceration; systemic fungal infections; diabetes (relative); concurrent NSAID; Demodex (immunosuppression worsens)",monitoring:"Glucose; CBC; electrolytes; urinalysis periodically; ACTH stim if chronic",notes:"Dogs convert prednisone to prednisolone in liver; cats may need prednisolone directly",alsoUsedIn:"Cats (use prednisolone); horses"},
  {genericName:"Prednisolone",brandNames:"Prednisolone",drugClass:"Corticosteroid (glucocorticoid; active form)",indications:"Same as prednisone; preferred in cats/hepatic disease",dosage:"Same as prednisone",route:"Oral; IV; ophthalmic",sideEffects:"Same as prednisone",warnings:"Same as prednisone",interactions:"Same as prednisone",foodInteractions:"Give with food",contraindications:"Same as prednisone",monitoring:"Same as prednisone",notes:"Active form; does not require hepatic conversion; preferred in cats and liver disease",alsoUsedIn:"Cats (preferred over prednisone); horses"},
  {genericName:"Dexamethasone",brandNames:"Dexamethasone; Azium",drugClass:"Corticosteroid (glucocorticoid; long-acting; very potent)",indications:"Cerebral edema; shock; IMHA/ITP; severe allergic reactions; diagnostic (low-dose dex suppression test)",dosage:"Anti-inflammatory: 0.1-0.2 mg/kg IV/PO; Immunosuppressive: 0.2-0.5 mg/kg; LDDS test: 0.01 mg/kg IV",route:"Oral; IV; IM; ophthalmic",sideEffects:"Same as prednisone but more potent/prolonged; pronounced PU/PD",warnings:"Same as prednisone; more potent HPA axis suppression; higher GI ulceration risk",interactions:"Same as prednisone",foodInteractions:"Give with food (oral)",contraindications:"Same as prednisone",monitoring:"Same as prednisone",notes:"~7x more potent than prednisone; no mineralocorticoid activity",alsoUsedIn:"Cats; horses"},
  {genericName:"Diphenhydramine",brandNames:"Benadryl",drugClass:"1st-generation antihistamine (H1 blocker)",indications:"Mild allergic reactions; urticaria; vaccine reactions; motion sickness; mild sedation",dosage:"2-4 mg/kg PO q8-12h; 1-2 mg/kg IM/IV (acute reactions)",route:"Oral; IM; IV",sideEffects:"Sedation; dry mouth; urinary retention; GI upset",warnings:"Anticholinergic toxicity at high doses; CNS stimulation paradoxically in some dogs",interactions:"CNS depressants (enhanced sedation); anticholinergic drugs (additive)",foodInteractions:"Give with food",contraindications:"Glaucoma; urinary retention; GI obstruction",monitoring:"None routine",notes:"Check formulation for xylitol-free; limited efficacy for atopy",alsoUsedIn:"Cats (lower dose)"},
  {genericName:"Cetirizine",brandNames:"Zyrtec",drugClass:"2nd-generation antihistamine (H1 blocker)",indications:"Atopic dermatitis (mild); urticaria; allergic pruritus (adjunct)",dosage:"1-2 mg/kg PO q12-24h",route:"Oral",sideEffects:"Mild sedation; GI upset; dry mouth",warnings:"Few serious side effects",interactions:"Minimal interactions; avoid with other antihistamines",foodInteractions:"Give with or without food",contraindications:"Adjust dose in renal impairment",monitoring:"None routine",notes:"Less sedating than diphenhydramine; limited efficacy as monotherapy for atopy",alsoUsedIn:"Cats"},
  {genericName:"Hydroxyzine",brandNames:"Atarax; Vistaril",drugClass:"1st-generation antihistamine / anxiolytic",indications:"Allergic pruritus; atopic dermatitis; anxiety; urticaria",dosage:"2 mg/kg PO q8-12h",route:"Oral",sideEffects:"Sedation; dry mouth; GI upset",warnings:"Anticholinergic effects at high doses; QT prolongation (rare)",interactions:"CNS depressants; anticholinergics; QT-prolonging drugs",foodInteractions:"Give with food",contraindications:"Glaucoma; urinary retention; cardiac arrhythmias",monitoring:"None routine",notes:"Most effective antihistamine for canine pruritus (studies)",alsoUsedIn:"Cats"},
  {genericName:"Pentoxifylline",brandNames:"Trental",drugClass:"Methylxanthine rheological agent",indications:"Dermatomyositis; vasculitis; contact dermatitis; atopic dermatitis adjunct; ischemic dermatopathies",dosage:"10-25 mg/kg PO q8-12h",route:"Oral",sideEffects:"GI upset; vomiting; dizziness",warnings:"Rare bleeding; hypotension",interactions:"Anticoagulants/antiplatelets (increased bleeding risk); theophylline (increased levels); antihypertensives",foodInteractions:"Give with food",contraindications:"Active bleeding; recent hemorrhage",monitoring:"None routine",notes:"Improves microcirculation; immunomodulatory; often combined with niacinamide",alsoUsedIn:"Cats (off-label)"},
  {genericName:"Azathioprine",brandNames:"Imuran",drugClass:"Purine antagonist immunosuppressant",indications:"IMHA; IMPA; ITP; IBD; pemphigus; myasthenia gravis (steroid-sparing)",dosage:"2 mg/kg PO q24h x14d then q48h",route:"Oral",sideEffects:"Bone marrow suppression; GI upset; hepatotoxicity; pancreatitis",warnings:"Myelosuppression (dose-limiting); hepatotoxicity; pancreatitis; increased infection/neoplasia risk",interactions:"Allopurinol (SEVERE toxicity; must reduce dose 25-33% or avoid); ACE inhibitors (myelosuppression); other immunosuppressants",foodInteractions:"Give with food",contraindications:"CATS (FATAL myelosuppression; use chlorambucil instead); bone marrow disease; serious infections",monitoring:"CBC weekly x8wks then q2wks x3mo then monthly; liver values monthly",notes:"ABSOLUTE CONTRAINDICATION IN CATS; 5-7 day onset of immunosuppression",alsoUsedIn:"Dogs only"},
  {genericName:"Mycophenolate",brandNames:"CellCept; Myfortic",drugClass:"Purine synthesis inhibitor immunosuppressant",indications:"IMHA; ITP; IMPA; pemphigus; steroid-sparing in immune-mediated diseases",dosage:"10-20 mg/kg PO q12h",route:"Oral",sideEffects:"GI upset (dose-limiting); diarrhea; bone marrow suppression",warnings:"Severe GI toxicity; myelosuppression; increased infection risk; teratogenic",interactions:"Antacids/proton pump inhibitors (reduce absorption); azathioprine (overlapping toxicity); cholestyramine (reduces levels)",foodInteractions:"Give on empty stomach (food reduces absorption)",contraindications:"Pregnancy; serious infections; concurrent azathioprine",monitoring:"CBC/chemistry q1-2wks initially then monthly",notes:"Often replaces azathioprine when GI is tolerated",alsoUsedIn:"Cats; dogs"},
  {genericName:"Pimobendan",brandNames:"Vetmedin",drugClass:"Inodilator (PDE-III inhibitor + calcium sensitizer)",indications:"Dilated cardiomyopathy; congestive heart failure (MMVD stage B2/C/D)",dosage:"0.25-0.3 mg/kg PO q12h",route:"Oral (chewable)",sideEffects:"Decreased appetite; diarrhea; lethargy",warnings:"Arrhythmias (rare); may accelerate disease in subclinical HCM (cats)",interactions:"Minimal significant interactions; use cautiously with other positive inotropes",foodInteractions:"Give 1 hour before food (food reduces absorption)",contraindications:"Aortic stenosis; HOCM; hypertrophic obstructive conditions",monitoring:"Echocardiogram q6-12mo; chest x-ray; arrhythmia monitoring",notes:"MUST give on empty stomach (1hr before meals); EPIC trial landmark for pre-CHF use",alsoUsedIn:"Cats (off-label; caution in HCM)"},
  {genericName:"Enalapril",brandNames:"Enacard; Vasotec",drugClass:"ACE inhibitor",indications:"Congestive heart failure; protein-losing nephropathy; systemic hypertension",dosage:"0.5 mg/kg PO q12-24h",route:"Oral",sideEffects:"Hypotension; azotemia; decreased appetite; GI upset; hyperkalemia",warnings:"Hypotension; acute renal failure (especially with NSAIDs/diuretics); hyperkalemia",interactions:"NSAIDs (reduce efficacy; increase renal risk); potassium-sparing diuretics (hyperkalemia); furosemide (hypotension initially then synergy)",foodInteractions:"Give with or without food",contraindications:"Bilateral renal artery stenosis; severe hypotension; dehydration",monitoring:"BUN/creatinine/electrolytes at 3-7 days then q3-6mo; blood pressure",notes:"Titrate slowly; check renal values before dose increases",alsoUsedIn:"Cats"},
  {genericName:"Benazepril",brandNames:"Fortekor; Lotensin",drugClass:"ACE inhibitor",indications:"CHF; chronic kidney disease (CKD); proteinuria; systemic hypertension",dosage:"0.25-0.5 mg/kg PO q12-24h",route:"Oral",sideEffects:"Same as enalapril",warnings:"Same as enalapril",interactions:"Same as enalapril",foodInteractions:"Give with or without food",contraindications:"Same as enalapril",monitoring:"Same as enalapril",notes:"Preferred ACEI in renal disease (hepatic + renal excretion)",alsoUsedIn:"Cats (primary ACEI)"},
  {genericName:"Furosemide",brandNames:"Lasix; Salix",drugClass:"Loop diuretic",indications:"Congestive heart failure (pulmonary edema); ascites; edema; oliguric renal failure",dosage:"2-6 mg/kg IV/IM/PO q8-12h (CHF); up to 12 mg/kg/hr CRI (acute pulmonary edema)",route:"Oral; IV; IM",sideEffects:"Dehydration; hypokalemia; hyponatremia; azotemia; ototoxicity (IV bolus)",warnings:"Severe electrolyte derangements; dehydration; ototoxicity (especially with aminoglycosides); hypokalemia potentiates digoxin toxicity",interactions:"Aminoglycosides (ototoxicity; nephrotoxicity); digoxin (hypokalemia increases toxicity); NSAIDs (reduce diuretic effect); ACE inhibitors (synergy but monitor); corticosteroids (hypokalemia)",foodInteractions:"Give with or without food",contraindications:"Severe dehydration; anuria; uncorrected electrolyte depletion",monitoring:"Electrolytes (K+; Na+); BUN/creatinine; hydration status; respiratory rate q1-3mo",notes:"Home respiratory rate monitoring for CHF patients",alsoUsedIn:"Cats; horses"},
  {genericName:"Spironolactone",brandNames:"Aldactone; Prilactone",drugClass:"Potassium-sparing diuretic (aldosterone antagonist)",indications:"CHF adjunct; ascites; aldosterone escape; anti-fibrotic cardiac effects",dosage:"1-2 mg/kg PO q12h",route:"Oral",sideEffects:"Hyperkalemia; GI upset; facial dermatitis (cats)",warnings:"Hyperkalemia (especially with ACE inhibitors); facial dermatitis in cats",interactions:"ACE inhibitors (hyperkalemia risk); other potassium-sparing agents; digoxin (displaces from protein binding); NSAIDs",foodInteractions:"Give with food (increases absorption)",contraindications:"Addison's disease; hyperkalemia; severe renal failure",monitoring:"Electrolytes (K+) within 1wk then q3-6mo; renal values",notes:"Mild diuretic; main value is anti-fibrotic and neurohormonal modulation",alsoUsedIn:"Cats (facial dermatitis risk)"},
  {genericName:"Diltiazem",brandNames:"Cardizem; Dilacor",drugClass:"Calcium channel blocker (benzothiazepine)",indications:"Supraventricular tachycardia; atrial fibrillation rate control; HCM (cats)",dosage:"Dogs: 0.5-2 mg/kg PO q8h; Cats: 7.5 mg/cat PO q8h",route:"Oral; IV",sideEffects:"Bradycardia; hypotension; GI upset; lethargy",warnings:"AV block; severe bradycardia; hypotension; heart failure exacerbation",interactions:"Beta-blockers (severe bradycardia/AV block; avoid combining in dogs); digoxin (increased levels); cyclosporine (increased levels); phenobarbital (decreased diltiazem levels)",foodInteractions:"Give with food",contraindications:"Severe LV dysfunction; sick sinus syndrome; AV block; severe hypotension",monitoring:"ECG; heart rate; blood pressure; renal function",notes:"Do not combine with beta-blockers in dogs without cardiology guidance",alsoUsedIn:"Cats (HCM; SVT)"},
  {genericName:"Atenolol",brandNames:"Tenormin",drugClass:"Beta-blocker (beta-1 selective)",indications:"Supraventricular arrhythmias; ventricular arrhythmias; aortic stenosis; systemic hypertension",dosage:"0.25-1 mg/kg PO q12-24h",route:"Oral",sideEffects:"Bradycardia; hypotension; lethargy; bronchospasm; weakness",warnings:"Severe bradycardia; AV block; negative inotropy (worsens CHF)",interactions:"Calcium channel blockers (severe bradycardia; avoid); insulin/oral hypoglycemics (masks hypoglycemia signs); NSAIDs (reduce effect)",foodInteractions:"Give with or without food",contraindications:"Overt CHF; sick sinus syndrome; AV block; severe bradycardia; reactive airway disease",monitoring:"Heart rate; blood pressure; ECG",notes:"Do not stop abruptly (rebound tachycardia)",alsoUsedIn:"Cats (common for HCM/thyrotoxicosis)"},
  {genericName:"Digoxin",brandNames:"Lanoxin; Cardoxin",drugClass:"Cardiac glycoside",indications:"Atrial fibrillation rate control; supraventricular tachycardia; systolic heart failure",dosage:"0.005-0.01 mg/kg PO q12h (dose by lean body weight)",route:"Oral; IV",sideEffects:"Anorexia; vomiting; diarrhea; arrhythmias; lethargy",warnings:"NARROW therapeutic index; digoxin toxicity (arrhythmias; GI; neuro); FATAL with hypercalcemia/hypokalemia",interactions:"Furosemide (hypokalemia increases toxicity); quinidine/verapamil/amiodarone (increase levels); antacids (decrease absorption); calcium gluconate (FATAL arrhythmia)",foodInteractions:"Give 1h before or 2h after food; consistent timing",contraindications:"Hypokalemia; hypercalcemia; renal failure (dose reduce); VPCs; ventricular tachycardia; WPW",monitoring:"Serum digoxin levels 8-10h post-dose (target 1.0-2.0 ng/mL); electrolytes; renal values; ECG",notes:"Dose by LEAN body weight; keep K+ normal; very narrow therapeutic index",alsoUsedIn:"Cats (lower doses)"},
  {genericName:"Clopidogrel",brandNames:"Plavix",drugClass:"Antiplatelet (ADP receptor inhibitor)",indications:"Arterial thromboembolism prevention (cats); IMHA adjunct; cardiac disease; post-stent",dosage:"1-2 mg/kg PO q24h (dogs); 18.75 mg/cat PO q24h",route:"Oral",sideEffects:"Bleeding; GI upset; rarely hepatotoxicity",warnings:"Bleeding risk; thrombocytopenia (rare)",interactions:"Omeprazole (may reduce activation; debated); NSAIDs/aspirin (increased bleeding); anticoagulants (additive bleeding)",foodInteractions:"Give with food",contraindications:"Active bleeding; thrombocytopenia; planned surgery (stop 5-7d before)",monitoring:"CBC; watch for bleeding",notes:"Prodrug; requires hepatic activation; omeprazole interaction debated",alsoUsedIn:"Cats (primary indication: ATE prevention)"},
  {genericName:"Amlodipine",brandNames:"Norvasc",drugClass:"Calcium channel blocker (dihydropyridine)",indications:"Systemic hypertension; secondary to CKD/hyperthyroidism/hyperaldosteronism",dosage:"Dogs: 0.1-0.5 mg/kg PO q24h; Cats: 0.625-1.25 mg/cat PO q24h",route:"Oral",sideEffects:"Hypotension; tachycardia; gingival hyperplasia (rare); edema",warnings:"Severe hypotension",interactions:"ACE inhibitors (synergistic hypotension; may be intentional); beta-blockers; other antihypertensives",foodInteractions:"Give with or without food",contraindications:"Severe aortic stenosis; severe hypotension",monitoring:"Blood pressure q1-2wks until stable; renal values; fundic exam",notes:"First-line for feline systemic hypertension",alsoUsedIn:"Cats (primary use)"},
  {genericName:"Omeprazole",brandNames:"Prilosec; Gastrogard",drugClass:"Proton pump inhibitor",indications:"GI ulceration; erosive esophagitis; GERD; mast cell tumor (histamine-mediated acid)",dosage:"1-2 mg/kg PO q12-24h",route:"Oral",sideEffects:"GI upset (rare); altered gut flora",warnings:"Chronic use may alter calcium absorption; bacterial overgrowth; rebound acid hypersecretion on withdrawal",interactions:"Clopidogrel (may reduce activation); ketoconazole/itraconazole (reduced absorption due to decreased acid); diazepam/phenytoin (increased levels); sucralfate (give 30min apart)",foodInteractions:"Give 30min before food on empty stomach for best efficacy",contraindications:"Few absolute; chronic use warrants periodic reassessment",monitoring:"None routine; B12 if chronic",notes:"Taper off rather than abrupt stop to avoid rebound",alsoUsedIn:"Cats; horses"},
  {genericName:"Famotidine",brandNames:"Pepcid",drugClass:"H2 receptor antagonist",indications:"Gastric ulcers; GERD; acid-related GI disease; uremic gastritis",dosage:"0.5-1 mg/kg PO/IV q12-24h",route:"Oral; IV",sideEffects:"Generally very safe; rare GI upset",warnings:"Rare: cardiac arrhythmias (rapid IV push); thrombocytopenia",interactions:"Ketoconazole/itraconazole (reduced absorption); antacids (minimal)",foodInteractions:"Give with or without food",contraindications:"Few contraindications",monitoring:"None routine",notes:"Less potent acid suppression than omeprazole; safer profile; often first choice",alsoUsedIn:"Cats"},
  {genericName:"Sucralfate",brandNames:"Carafate",drugClass:"Mucosal protectant",indications:"GI ulcers; esophagitis; erosions; uremic stomatitis",dosage:"0.5-1 g/dog PO q8-12h (large dog); 0.25-0.5 g (small dog)",route:"Oral (slurry or tablet)",sideEffects:"Constipation",warnings:"Minimal systemic absorption so few systemic effects",interactions:"Binds many drugs reducing their absorption (tetracyclines; fluoroquinolones; digoxin; phenytoin; ketoconazole); give other meds 2h before sucralfate",foodInteractions:"Give on empty stomach 1h before meals; give other medications 2h before sucralfate",contraindications:"Few absolute",monitoring:"None routine",notes:"Physical barrier; must give on empty stomach; separate from all other drugs",alsoUsedIn:"Cats"},
  {genericName:"Maropitant",brandNames:"Cerenia",drugClass:"NK1 receptor antagonist (antiemetic)",indications:"Vomiting (acute/chronic); motion sickness; visceral pain adjunct; nausea",dosage:"2 mg/kg PO q24h (vomiting); 8 mg/kg PO (motion sickness); 1 mg/kg SC q24h",route:"Oral; SC",sideEffects:"SC injection stinging/pain (store refrigerated to reduce); drowsiness; drooling",warnings:"Rare allergic reactions; bone marrow effects at very high research doses only",interactions:"Highly protein-bound (may displace other bound drugs theoretically); erythromycin (interaction in lab)",foodInteractions:"Give with light meal to improve absorption; tablets with or without food",contraindications:"<16 weeks (injection); <8 weeks (oral per label); bone marrow suppression at supratherapeutic doses",monitoring:"None routine",notes:"Refrigerate injectable to reduce injection site sting; most effective antiemetic in dogs",alsoUsedIn:"Cats (off-label; widely used)"},
  {genericName:"Metoclopramide",brandNames:"Reglan",drugClass:"Dopamine antagonist prokinetic/antiemetic",indications:"GI motility disorders; nausea/vomiting; gastroparesis; GERD",dosage:"0.2-0.5 mg/kg PO/SC q6-8h; 1-2 mg/kg/day CRI",route:"Oral; SC; IV (CRI)",sideEffects:"Restlessness; behavioral changes; drowsiness; diarrhea",warnings:"Extrapyramidal signs (tremors; agitation); contraindicated with GI obstruction",interactions:"Opioids (antagonized motility effect); phenothiazines (increased extrapyramidal risk); anticholinergics (antagonized); cisapride (avoid combo)",foodInteractions:"Give 30min before meals",contraindications:"GI obstruction/perforation; pheochromocytoma; seizure disorders; concurrent phenothiazines",monitoring:"None routine",notes:"Do NOT use with suspected GI obstruction; CRI preferred for hospitalized patients",alsoUsedIn:"Cats"},
  {genericName:"Ondansetron",brandNames:"Zofran",drugClass:"5-HT3 antagonist antiemetic",indications:"Chemotherapy-induced vomiting; severe nausea; gastroenteritis",dosage:"0.5-1 mg/kg PO/IV q8-12h",route:"Oral; IV",sideEffects:"Constipation; headache (presumed); sedation",warnings:"QT prolongation (rare at standard doses); serotonin syndrome (with serotonergic drugs)",interactions:"Serotonergic drugs (serotonin syndrome); QT-prolonging drugs; tramadol (may reduce analgesic effect)",foodInteractions:"Give with or without food",contraindications:"QT prolongation; serotonin syndrome risk combo",monitoring:"ECG if QT concern",notes:"Often used rescue antiemetic when maropitant insufficient",alsoUsedIn:"Cats"},
  {genericName:"Capromorelin",brandNames:"Entyce",drugClass:"Ghrelin receptor agonist (appetite stimulant)",indications:"Appetite stimulation in dogs; CKD-associated inappetence",dosage:"3 mg/kg PO q24h",route:"Oral liquid",sideEffects:"Diarrhea; vomiting; polydipsia; hypersalivation",warnings:"Fluid overload (stimulates GH/IGF-1); not for pituitary-dependent conditions",interactions:"None significant reported",foodInteractions:"Give on empty stomach or with food",contraindications:"Pituitary-dependent hyperadrenocorticism (theoretical); actively vomiting (won't retain)",monitoring:"Body weight; appetite log",notes:"FDA-approved canine appetite stimulant; liquid formulation",alsoUsedIn:"Dogs (Elura/capromorelin approved separately for cats)"},
  {genericName:"Mirtazapine",brandNames:"Remeron; Mirataz (transdermal for cats)",drugClass:"Tetracyclic antidepressant/appetite stimulant",indications:"Appetite stimulation; nausea reduction",dosage:"Dogs: 1.88 mg/dog q24h (small) to 30 mg/dog q24h (large); Cats: 1.88 mg PO q48-72h or Mirataz transdermal",route:"Oral; transdermal (cats)",sideEffects:"Sedation; vocalization; restlessness; serotonin effects (high dose)",warnings:"Serotonin syndrome (with serotonergic drugs); sedation",interactions:"SSRIs; MAOIs (CONTRAINDICATED); tramadol; cyproheptadine (antagonizes appetite effect); CNS depressants",foodInteractions:"Give with or without food",contraindications:"MAOI use; liver disease (reduce dose); serotonergic drug combinations",monitoring:"None routine; liver function if hepatic disease",notes:"Mirataz transdermal FDA-approved for cats only; dose reduce in hepatic/renal disease",alsoUsedIn:"Cats (primary species)"},
  {genericName:"Ursodiol",brandNames:"Actigall; Ursofalk",drugClass:"Bile acid (choleretic/hepatoprotective)",indications:"Hepatobiliary disease; cholestasis; gallbladder mucocele (medical management); chronic hepatitis",dosage:"10-15 mg/kg PO q24h or divided q12h",route:"Oral",sideEffects:"Diarrhea (uncommon)",warnings:"Rare GI upset; not effective if complete bile duct obstruction",interactions:"Antacids/cholestyramine (reduce absorption); cyclosporine (increased absorption)",foodInteractions:"Give with food",contraindications:"Complete bile duct obstruction",monitoring:"Liver values; bile acids; ultrasound for mucocele",notes:"Often combined with SAMe/silymarin for liver support triad",alsoUsedIn:"Cats"},
  {genericName:"Lactulose",brandNames:"Cephulac; Enulose",drugClass:"Osmotic laxative / ammonia trapper",indications:"Constipation; hepatic encephalopathy (reduces ammonia); megacolon adjunct",dosage:"Constipation: 1 mL/4.5 kg PO q8-12h; Hepatic encephalopathy: titrate to 2-3 soft stools/day",route:"Oral; rectal",sideEffects:"Diarrhea; gas; cramping",warnings:"Electrolyte loss with excessive diarrhea",interactions:"Antacids (reduce ammonia-trapping efficacy); neomycin (synergy for hepatic encephalopathy)",foodInteractions:"Give with or without food; may mix with food/water",contraindications:"None absolute",monitoring:"Stool quality; ammonia levels in hepatic encephalopathy",notes:"Titrate dose to stool consistency",alsoUsedIn:"Cats"},
  {genericName:"Levothyroxine",brandNames:"Soloxine; Thyro-Tabs",drugClass:"Thyroid hormone replacement",indications:"Hypothyroidism",dosage:"0.02 mg/kg PO q12h (start); adjust per T4 levels",route:"Oral",sideEffects:"Tachycardia; panting; PU/PD; restlessness (overdose signs)",warnings:"Thyrotoxicosis if overdosed; cardiac effects",interactions:"Insulin (may increase requirements); cardiac drugs (dose adjustment needed); phenobarbital (increases metabolism); calcium/sucralfate/iron (reduce absorption)",foodInteractions:"Give on empty stomach consistently; or consistently with food; separate from calcium/iron/antacids by 4h",contraindications:"Pre-existing cardiac arrhythmias (start low dose); adrenal insufficiency (correct first)",monitoring:"T4 level 4-6h post-pill at 4wk then q6-12mo; target upper half of reference; TSH if available",notes:"Dose adjustments based on clinical signs + T4 level; not T4 alone",alsoUsedIn:"Cats (rare hypothyroidism)"},
  {genericName:"Trilostane",brandNames:"Vetoryl",drugClass:"3-beta-hydroxysteroid dehydrogenase inhibitor",indications:"Hyperadrenocorticism (Cushing's disease/syndrome)",dosage:"1-2 mg/kg PO q12h (start low; titrate)",route:"Oral",sideEffects:"Lethargy; decreased appetite; vomiting; diarrhea; weakness",warnings:"Adrenal necrosis; Addisonian crisis (hypocortisolism); electrolyte derangements; sudden death (rare)",interactions:"Ketoconazole (additive adrenal suppression); ACE inhibitors (potentiate hypotension); potassium-sparing diuretics",foodInteractions:"Give with food (increases absorption)",contraindications:"Hepatic disease; renal disease; breeding animals",monitoring:"ACTH stimulation test at 10-14d then 30d then q3-6mo (target post-ACTH cortisol 1.5-5.5 mcg/dL); electrolytes; chemistry",notes:"Have prednisone on hand for owner to give if Addisonian signs appear; ACTH stim timing is critical",alsoUsedIn:"Dogs primarily; cats (off-label)"},
  {genericName:"Methimazole",brandNames:"Tapazole; Felimazole",drugClass:"Thioamide antithyroid",indications:"Hyperthyroidism (primarily cats; rare in dogs)",dosage:"Cats: 2.5 mg PO q12h (start); Dogs: 2-5 mg/kg q12h",route:"Oral; transdermal (cats)",sideEffects:"GI upset; lethargy; facial excoriation (cats); blood dyscrasias",warnings:"Bone marrow suppression (agranulocytosis; thrombocytopenia); hepatotoxicity; facial pruritus (cats); may unmask CKD",interactions:"Phenobarbital (may alter thyroid levels); anticoagulants (potentiated); digoxin (altered levels as thyroid normalizes)",foodInteractions:"Give with or without food; transdermal on hairless ear pinna (cats)",contraindications:"Hepatic disease; autoimmune disease; bone marrow disorders",monitoring:"CBC/chemistry/T4 at 2-4wks then q3-6mo; renal values (unmasking CKD); liver values",notes:"Primarily feline drug; transdermal compounded option for non-pillable cats",alsoUsedIn:"Cats (primary); dogs (rare)"},
  {genericName:"Insulin NPH",brandNames:"Humulin N; Novolin N; Vetsulin (porcine lente)",drugClass:"Intermediate-acting insulin",indications:"Diabetes mellitus",dosage:"Dogs: 0.25-0.5 U/kg SC q12h (start); titrate per glucose curves",route:"Subcutaneous injection",sideEffects:"Hypoglycemia; injection site reactions; weight gain",warnings:"HYPOGLYCEMIA (emergency); insulin resistance; Somogyi effect (rebound hyperglycemia from overdose)",interactions:"Corticosteroids (antagonize); thiazides (antagonize); beta-blockers (mask hypoglycemia); anabolic steroids (increase sensitivity)",foodInteractions:"N/A (injectable); consistent feeding schedule critical",contraindications:"None absolute; dose adjust frequently",monitoring:"Blood glucose curves; fructosamine q2-4wks; clinical signs (PU/PD; weight)",notes:"Have corn syrup/honey available for hypoglycemia; insulin type varies by species preference",alsoUsedIn:"Dogs (NPH or Vetsulin); cats (glargine/PZI preferred)"},
  {genericName:"Fenbendazole",brandNames:"Panacur; Safe-Guard",drugClass:"Benzimidazole anthelmintic",indications:"Roundworms; hookworms; whipworms; Giardia; Taenia; some lungworms",dosage:"50 mg/kg PO q24h x3-5d (routine); x5d (Giardia)",route:"Oral",sideEffects:"Generally very safe; rarely GI upset",warnings:"Bone marrow suppression at very high doses/prolonged use (rare; idiosyncratic)",interactions:"Minimal interactions",foodInteractions:"Give with food (increases absorption)",contraindications:"None significant",monitoring:"None routine",notes:"Very wide safety margin; safe in pregnancy; OTC",alsoUsedIn:"Cats; horses; livestock; exotics"},
  {genericName:"Pyrantel",brandNames:"Nemex; Strongid",drugClass:"Tetrahydropyrimidine anthelmintic",indications:"Roundworms; hookworms",dosage:"5-10 mg/kg PO once; repeat in 2-3wks",route:"Oral",sideEffects:"Vomiting (uncommon)",warnings:"Very safe; minimal toxicity",interactions:"Levamisole; morantel (antagonism); organophosphates (avoid combo)",foodInteractions:"Give with or without food",contraindications:"None significant",monitoring:"None routine",notes:"Puppy dewormer; very safe; OTC; ingredient in many heartworm preventives",alsoUsedIn:"Cats; horses; livestock"},
  {genericName:"Praziquantel",brandNames:"Droncit; Drontal (combo)",drugClass:"Isoquinolone anthelmintic",indications:"Tapeworms (Dipylidium; Taenia; Echinococcus); flukes",dosage:"5 mg/kg PO/SC once (tapeworms); higher for flukes",route:"Oral; SC",sideEffects:"GI upset; injection site pain; lethargy; drooling",warnings:"Very safe; rare anaphylaxis at injection",interactions:"Minimal significant interactions",foodInteractions:"Give with or without food",contraindications:"<4 weeks age (per label)",monitoring:"None routine",notes:"Often combined with pyrantel or fenbendazole in broad-spectrum dewormers",alsoUsedIn:"Cats; horses; exotics"},
  {genericName:"Ivermectin",brandNames:"Heartgard; Ivomec",drugClass:"Avermectin (macrocyclic lactone)",indications:"Heartworm prevention; Demodex (off-label high dose); ear mites; sarcoptic mange",dosage:"Heartworm prevention: 6-12 mcg/kg PO monthly; Demodex: 300-600 mcg/kg PO daily (off-label)",route:"Oral; SC; topical",sideEffects:"Safe at preventive doses; tremors; ataxia; blindness; death at high doses in MDR1 dogs",warnings:"MDR1/ABCB1 MUTATION: FATAL NEUROTOXICITY at demodex doses in Collies and related breeds; blindness; seizures; coma; death",interactions:"P-glycoprotein inhibitors (ketoconazole; spinosad; cyclosporine) increase toxicity risk; spinosad combination linked to ivermectin toxicity reports",foodInteractions:"Give with food (oral preventive)",contraindications:"MDR1/ABCB1 mutant dogs at high doses (>50 mcg/kg); heartworm-positive dogs (reaction risk; must be managed)",monitoring:"Heartworm test before starting prevention annually",notes:"Safe at heartworm-preventive doses in all breeds; HIGH DOSE requires MDR1 testing first",alsoUsedIn:"Cats; horses; livestock; exotics"},
  {genericName:"Milbemycin Oxime",brandNames:"Interceptor; Sentinel",drugClass:"Milbemycin (macrocyclic lactone)",indications:"Heartworm prevention; roundworms; hookworms; whipworms; Demodex (off-label)",dosage:"Heartworm prevention: 0.5-1 mg/kg PO monthly; Demodex: 1-2 mg/kg PO daily",route:"Oral",sideEffects:"Safe at preventive doses; depression; ataxia at high doses in MDR1 dogs",warnings:"MDR1 sensitivity at demodex treatment doses (same as ivermectin class)",interactions:"Same MDR1-relevant interactions as ivermectin",foodInteractions:"Give with food",contraindications:"MDR1 dogs at high doses; heartworm-positive dogs",monitoring:"Heartworm test annually",notes:"Wider safety margin than ivermectin in MDR1 dogs at preventive doses",alsoUsedIn:"Cats; ferrets"},
  {genericName:"Afoxolaner",brandNames:"NexGard; NexGard Plus (with moxidectin + pyrantel)",drugClass:"Isoxazoline",indications:"Fleas; ticks (multiple species); Demodex; Sarcoptes",dosage:"Dogs: per weight bracket chewable tablet PO monthly",route:"Oral chewable",sideEffects:"Vomiting; diarrhea; lethargy; decreased appetite",warnings:"FDA BOXED WARNING: seizures; tremors; ataxia in dogs with or without seizure history (isoxazoline class)",interactions:"Few drug interactions; caution combining with other seizure threshold-lowering drugs",foodInteractions:"Give with or without food",contraindications:"<8 weeks; <4 lbs; seizure history (relative; weigh risk/benefit)",monitoring:"None routine",notes:"Isoxazoline class; systemic flea/tick; also treats Demodex and Sarcoptes at standard dose",alsoUsedIn:"Dogs only"},
  {genericName:"Fluralaner",brandNames:"Bravecto",drugClass:"Isoxazoline",indications:"Fleas; ticks; Demodex; Sarcoptes",dosage:"Per weight bracket; chewable PO q12wks; topical q12wks",route:"Oral; topical",sideEffects:"Vomiting; diarrhea; decreased appetite; lethargy",warnings:"FDA BOXED WARNING: seizures; tremors; ataxia (isoxazoline class)",interactions:"Few significant; same isoxazoline cautions",foodInteractions:"Give with food (oral; increases absorption)",contraindications:"<6 months; <4.4 lbs; seizure history (relative)",monitoring:"None routine",notes:"12-week duration; available oral and topical",alsoUsedIn:"Dogs; cats (topical)"},
  {genericName:"Sarolaner",brandNames:"Simparica; Simparica Trio (with moxidectin + pyrantel)",drugClass:"Isoxazoline",indications:"Fleas; ticks; Demodex; Sarcoptes; heartworm prevention (Trio)",dosage:"Per weight bracket PO monthly",route:"Oral chewable",sideEffects:"Vomiting; diarrhea; lethargy",warnings:"FDA BOXED WARNING: seizures; tremors; ataxia (isoxazoline class)",interactions:"Few significant; same isoxazoline cautions",foodInteractions:"Give with or without food",contraindications:"<6 months; <2.8 lbs; seizure history (relative)",monitoring:"Heartworm test annually (Trio)",notes:"Simparica Trio is all-in-one: fleas/ticks/heartworm/intestinal worms",alsoUsedIn:"Dogs only"},
  {genericName:"Selamectin",brandNames:"Revolution; Revolution Plus (cats: + sarolaner)",drugClass:"Avermectin (macrocyclic lactone; topical)",indications:"Heartworm prevention; fleas; ear mites; sarcoptic mange; roundworms (cats); hookworms (cats)",dosage:"6-12 mg/kg topical monthly",route:"Topical",sideEffects:"Transient hair loss at application site; lethargy; GI upset (rare)",warnings:"MDR1 sensitivity at high doses (same class); generally very safe topically",interactions:"MDR1-relevant interactions at supratherapeutic doses",foodInteractions:"N/A (topical)",contraindications:"<6 weeks",monitoring:"Heartworm test annually",notes:"Topical so less GI concern; broad-spectrum",alsoUsedIn:"Cats; dogs"},
  {genericName:"Melarsomine",brandNames:"Immiticide",drugClass:"Organoarsenical adulticide",indications:"Heartworm adulticide treatment",dosage:"2.5 mg/kg deep IM (lumbar); AHS 3-dose protocol: Day 1; Day 60; Day 61",route:"Deep IM injection (lumbar epaxial muscles)",sideEffects:"Injection site pain/swelling; lethargy; coughing; fever",warnings:"Pulmonary thromboembolism (dying worms); injection site sterile abscess/necrosis; renal/hepatic toxicity",interactions:"Minimize exercise/activity for months post-treatment; concurrent doxycycline + prednisone per AHS protocol",foodInteractions:"N/A (injectable)",contraindications:"Severe Class 4 (caval syndrome); severe hepatic/renal disease",monitoring:"Antigen testing post-treatment at 6-12 months; monitor respiratory effort; exercise restriction CRITICAL",notes:"AHS 3-dose protocol is standard of care; strict exercise restriction is essential to reduce thromboembolism risk",alsoUsedIn:"Dogs only"},
  {genericName:"Cyclophosphamide",brandNames:"Cytoxan",drugClass:"Alkylating agent",indications:"Lymphoma (CHOP protocol); immune-mediated disease; various carcinomas",dosage:"200-250 mg/m2 PO/IV q3wks (lymphoma); 50 mg/m2 PO 4d/wk (metronomic)",route:"Oral; IV",sideEffects:"Bone marrow suppression; GI upset; alopecia (minimal in dogs)",warnings:"Sterile hemorrhagic cystitis (DOSE-LIMITING); myelosuppression; teratogenic",interactions:"Other myelosuppressive drugs; allopurinol; furosemide (bladder irritation)",foodInteractions:"Give in morning with access to water for frequent urination",contraindications:"Active UTI; pre-existing cystitis; bone marrow failure",monitoring:"CBC (nadir ~7-10d); urinalysis for hematuria; chemistry",notes:"Give with furosemide or saline diuresis to flush bladder; morning dosing + water access critical",alsoUsedIn:"Dogs; cats"},
  {genericName:"Doxorubicin",brandNames:"Adriamycin",drugClass:"Anthracycline",indications:"Lymphoma (CHOP protocol); osteosarcoma; hemangiosarcoma; carcinomas",dosage:"30 mg/m2 IV q3wks (dogs >10kg); 1 mg/kg (dogs <10kg); cumulative max 180-240 mg/m2",route:"IV only (SEVERE vesicant)",sideEffects:"Myelosuppression; GI upset; alopecia; orange-red urine; anaphylactoid reactions",warnings:"CUMULATIVE CARDIOTOXICITY (irreversible cardiomyopathy at >180-240 mg/m2); SEVERE perivascular necrosis if extravasation; myelosuppression",interactions:"Other cardiotoxins; myelosuppressive agents; MDR1 dogs (increased toxicity); P-gp inhibitors",foodInteractions:"N/A (IV only)",contraindications:"Pre-existing cardiac disease; cumulative dose exceeded; MDR1 mutation (reduce dose 25-50%)",monitoring:"Echocardiogram before each dose or q2 cycles; CBC at nadir (7-10d); cardiac function monitoring",notes:"Strict IV placement; vesicant; have dexrazoxane available; cumulative dose cap",alsoUsedIn:"Dogs; cats"},
  {genericName:"Vincristine",brandNames:"Oncovin",drugClass:"Vinca alkaloid",indications:"Lymphoma (CHOP protocol); TVT; ITP (platelet release)",dosage:"0.5-0.7 mg/m2 IV weekly (CHOP) or q7d (ITP)",route:"IV only (SEVERE vesicant)",sideEffects:"Myelosuppression (mild); GI upset; peripheral neuropathy; constipation",warnings:"SEVERE tissue necrosis if extravasation; ileus; peripheral neuropathy; myelosuppression",interactions:"MDR1 dogs (increased toxicity); other myelosuppressive agents; P-gp inhibitors",foodInteractions:"N/A (IV only)",contraindications:"MDR1 mutation (reduce dose); severe neuropathy; ileus",monitoring:"CBC; neurologic exam; monitor for constipation/ileus",notes:"Vesicant; strict IV only; MDR1 dogs need dose reduction or avoidance",alsoUsedIn:"Dogs; cats"},
  {genericName:"Lomustine",brandNames:"CeeNU; CCNU",drugClass:"Nitrosourea alkylating agent",indications:"Lymphoma (rescue); mast cell tumors; brain tumors; histiocytic sarcoma",dosage:"60-90 mg/m2 PO q3-6wks",route:"Oral",sideEffects:"Myelosuppression (delayed nadir 7-14d); hepatotoxicity; GI upset",warnings:"CUMULATIVE HEPATOTOXICITY (may be fatal); delayed severe myelosuppression",interactions:"Other hepatotoxic drugs; myelosuppressive agents",foodInteractions:"Give on empty stomach (variable absorption with food)",contraindications:"Severe hepatic disease; bone marrow failure",monitoring:"CBC at day 7 and day 14; liver values before each dose; chemistry",notes:"Liver damage can be irreversible and cumulative; monitor closely",alsoUsedIn:"Dogs; cats"},
  {genericName:"Toceranib",brandNames:"Palladia",drugClass:"Tyrosine kinase inhibitor (VEGFR; PDGFR; Kit)",indications:"Mast cell tumors (FDA-approved); various carcinomas/sarcomas",dosage:"2.5-3.25 mg/kg PO q48h (Mon-Wed-Fri or every other day)",route:"Oral",sideEffects:"GI upset; diarrhea; anorexia; neutropenia; lameness; muscle pain",warnings:"GI perforation/hemorrhage; hypertension; proteinuria; pancreatitis; hepatotoxicity",interactions:"NSAIDs (GI risk); other myelosuppressive agents; CYP substrates",foodInteractions:"Give with or without food",contraindications:"Active GI disease; uncontrolled bleeding; severe hepatic/renal disease",monitoring:"CBC/chemistry q2wks initially then monthly; urinalysis (proteinuria); blood pressure",notes:"FDA-approved for recurrent canine mast cell tumors; Mon-Wed-Fri dosing common",alsoUsedIn:"Dogs only"},
  {genericName:"Chlorambucil",brandNames:"Leukeran",drugClass:"Alkylating agent",indications:"Lymphoma (cats); CLL; immune-mediated disease (steroid-sparing); IBD",dosage:"Dogs: 4-6 mg/m2 PO q48h or metronomic; Cats: 2 mg/cat PO q48-72h",route:"Oral",sideEffects:"Myelosuppression (delayed); GI upset",warnings:"Bone marrow suppression; secondary leukemias (rare; chronic use)",interactions:"Other myelosuppressive drugs; azathioprine (overlapping toxicity)",foodInteractions:"Give on empty stomach or with food",contraindications:"Severe bone marrow suppression",monitoring:"CBC q2-4wks",notes:"Preferred alkylating agent in cats (instead of azathioprine); handle with gloves",alsoUsedIn:"Cats; dogs"},
  {genericName:"Neo-Poly-Dex Ophthalmic",brandNames:"Maxitrol; various",drugClass:"Triple antibiotic + corticosteroid ophthalmic",indications:"Bacterial conjunctivitis with inflammation; anterior uveitis adjunct; post-surgical eye",dosage:"1-2 drops affected eye q4-8h",route:"Ophthalmic drops/ointment",sideEffects:"Ocular irritation; increased intraocular pressure",warnings:"Corneal ulcer worsening (steroid component delays healing; risk of perforation/melting); glaucoma",interactions:"Minimal systemic interactions",foodInteractions:"N/A (topical ophthalmic)",contraindications:"Corneal ulcers (ABSOLUTE for steroid-containing); fungal/viral keratitis; glaucoma",monitoring:"Intraocular pressure; fluorescein stain before use (MUST rule out ulcer)",notes:"ALWAYS fluorescein stain before using any ophthalmic steroid; ulcer = NO steroid",alsoUsedIn:"Dogs; cats; horses"},
  {genericName:"Cyclosporine Ophthalmic",brandNames:"Optimmune (0.2% ointment)",drugClass:"Calcineurin inhibitor (ophthalmic)",indications:"Keratoconjunctivitis sicca (KCS/dry eye); pannus; chronic superficial keratitis",dosage:"1/4 inch strip to affected eye q12h",route:"Ophthalmic ointment",sideEffects:"Mild ocular irritation initially; conjunctival hyperemia",warnings:"Few systemic effects; rare hypersensitivity",interactions:"Minimal; topical corticosteroids may be used concurrently initially",foodInteractions:"N/A (topical ophthalmic)",contraindications:"Active ocular fungal infection",monitoring:"Schirmer tear test q4-8wks (expect improvement in 2-6wks)",notes:"Takes 2-6 weeks for tear production improvement; lifelong therapy usually",alsoUsedIn:"Dogs; cats; horses"},
  {genericName:"Latanoprost",brandNames:"Xalatan",drugClass:"Prostaglandin analog (glaucoma)",indications:"Glaucoma (reduces intraocular pressure)",dosage:"1 drop affected eye q12-24h",route:"Ophthalmic drops",sideEffects:"Miosis; ocular irritation; darkening of iris (long-term)",warnings:"Anterior uveitis exacerbation; contraindicated in lens luxation",interactions:"Minimal systemic; NSAIDs (may reduce efficacy)",foodInteractions:"N/A (topical ophthalmic)",contraindications:"Anterior lens luxation; active uveitis",monitoring:"Intraocular pressure q2-4wks; fundic exam",notes:"Emergency IOP reduction; often combined with dorzolamide/timolol",alsoUsedIn:"Dogs; cats"},
  {genericName:"Dorzolamide-Timolol",brandNames:"Cosopt",drugClass:"Carbonic anhydrase inhibitor + beta-blocker (ophthalmic)",indications:"Glaucoma",dosage:"1 drop affected eye q8-12h",route:"Ophthalmic drops",sideEffects:"Ocular irritation; stinging; blepharospasm",warnings:"Bradycardia; bronchospasm (timolol systemic absorption); corneal edema",interactions:"Systemic beta-blockers; calcium channel blockers (cardiac effects); systemic carbonic anhydrase inhibitors",foodInteractions:"N/A (topical ophthalmic)",contraindications:"Asthma/reactive airway disease (timolol); severe cardiac disease (AV block; CHF)",monitoring:"Intraocular pressure; heart rate",notes:"Timolol component can cause systemic beta-blockade; caution in cardiac patients",alsoUsedIn:"Dogs; cats"},
  {genericName:"Mometamax",brandNames:"Mometamax (gentamicin-mometasone-clotrimazole)",drugClass:"Otic combination (antibiotic + steroid + antifungal)",indications:"Otitis externa (bacterial + yeast)",dosage:"Per label; typically q24h into affected ear x7-14d",route:"Otic",sideEffects:"Transient ear discomfort; head shaking",warnings:"Ototoxicity if tympanic membrane is ruptured (gentamicin)",interactions:"Minimal systemic",foodInteractions:"N/A (otic)",contraindications:"Ruptured tympanic membrane (MUST verify intact before aminoglycoside-containing products)",monitoring:"Otoscopic exam; cytology; verify intact tympanum",notes:"ALWAYS check tympanic membrane before using aminoglycoside ear drops",alsoUsedIn:"Dogs; cats"},
  {genericName:"Posatex",brandNames:"Posatex (orbifloxacin-mometasone-posaconazole)",drugClass:"Otic combination (fluoroquinolone + steroid + antifungal)",indications:"Otitis externa (bacterial + yeast)",dosage:"4 drops affected ear q24h x7d",route:"Otic",sideEffects:"Transient ear discomfort",warnings:"Steroid effects if chronic use; ruptured TM concerns",interactions:"Minimal systemic",foodInteractions:"N/A (otic)",contraindications:"Ruptured tympanic membrane",monitoring:"Otoscopic exam; cytology",notes:"Safer than aminoglycoside-containing if TM status uncertain",alsoUsedIn:"Dogs"},
  {genericName:"Claro",brandNames:"Claro (florfenicol-terbinafine-mometasone)",drugClass:"Otic combination (antibiotic + antifungal + steroid; single-dose)",indications:"Otitis externa (single veterinary application)",dosage:"1 tube per affected ear; single application by veterinarian",route:"Otic (single-dose)",sideEffects:"Head shaking; ear discharge",warnings:"Ruptured TM; deafness if TM ruptured",interactions:"Minimal",foodInteractions:"N/A (otic)",contraindications:"Ruptured tympanic membrane",monitoring:"Follow-up exam in 30 days",notes:"Single-application by vet; no at-home dosing needed; persists 30 days",alsoUsedIn:"Dogs"},
  {genericName:"Atipamezole",brandNames:"Antisedan",drugClass:"Alpha-2 adrenergic antagonist (reversal agent)",indications:"Reversal of dexmedetomidine/medetomidine sedation",dosage:"Equal volume to dexmedetomidine given IM",route:"IM (preferred); IV (dilute; slow)",sideEffects:"Excitement; trembling; tachycardia; hypotension",warnings:"Rapid IV can cause excitement/hypertension; do not use to reverse other sedatives",interactions:"Reverses dexmedetomidine/medetomidine specifically; does NOT reverse opioid or other sedation",foodInteractions:"N/A",contraindications:"Not for reversing non-alpha-2 sedation",monitoring:"Heart rate; blood pressure post-reversal",notes:"IM preferred; IV should be slow and diluted",alsoUsedIn:"Dogs; cats; exotics"},
  {genericName:"Vitamin K1",brandNames:"Mephyton; Veta-K1",drugClass:"Fat-soluble vitamin / coagulation factor cofactor",indications:"Anticoagulant rodenticide toxicosis; warfarin overdose; coagulopathy",dosage:"2.5-5 mg/kg PO q12h (loading); then adjust; typically 4-6 weeks for 2nd gen rodenticides",route:"Oral; SC (NEVER IV)",sideEffects:"Anaphylaxis (IV; DO NOT GIVE IV); injection site reactions (SC)",warnings:"Anaphylaxis/death if given IV; SC hematomas",interactions:"Warfarin/anticoagulants (this is the antidote)",foodInteractions:"Give with fatty food (fat-soluble; dramatically increases absorption)",contraindications:"NEVER give IV (fatal anaphylaxis)",monitoring:"PT/PTT at 48h after stopping to confirm adequate clotting; may need 4-6wk course for 2nd-gen rodenticides",notes:"MUST be given with fatty food for absorption; NEVER IV; 2nd-gen rodenticides need weeks of treatment",alsoUsedIn:"Dogs; cats"},
  {genericName:"N-Acetylcysteine",brandNames:"Mucomyst; Acetadote",drugClass:"Antioxidant / glutathione precursor",indications:"Acetaminophen toxicosis antidote; hepatoprotectant",dosage:"Loading: 140 mg/kg PO/IV; then 70 mg/kg PO/IV q4h x17+ doses",route:"Oral; IV",sideEffects:"Vomiting; GI upset; anaphylactoid reaction (IV)",warnings:"Anaphylactoid reactions (IV; pretreat with antihistamine)",interactions:"Activated charcoal (may adsorb NAC; give NAC before or after charcoal window)",foodInteractions:"Give with food if PO (palatability); dilute IV",contraindications:"None absolute in toxicosis",monitoring:"Liver values; methemoglobin levels; acetaminophen levels if available",notes:"Begin immediately; do not wait for levels; most effective within 8-10h of ingestion",alsoUsedIn:"Dogs; cats"},
  {genericName:"Activated Charcoal",brandNames:"ToxiBan; Actidose",drugClass:"Adsorbent decontaminant",indications:"GI decontamination for recent toxin ingestion",dosage:"1-2 g/kg PO (with or without sorbitol cathartic)",route:"Oral; gastric tube",sideEffects:"Black stool; vomiting; aspiration risk",warnings:"Aspiration pneumonia (do NOT give to obtunded/seizing animals without airway protection); sorbitol component may cause dehydration",interactions:"Binds many oral medications (give medications at different time); does NOT adsorb: xylitol; ethanol; iron; lithium; mineral acids/alkalis",foodInteractions:"Give within 1-2h of ingestion for best effect",contraindications:"Caustic/corrosive ingestion; patient at aspiration risk (obtunded; seizing; no gag reflex)",monitoring:"Hydration if sorbitol given; respiratory status",notes:"Not effective for all toxins; works best within 1h of ingestion; may repeat without sorbitol",alsoUsedIn:"Dogs; cats"},
  {genericName:"Epinephrine",brandNames:"Adrenalin; EpiPen (human)",drugClass:"Catecholamine (alpha + beta agonist)",indications:"Anaphylaxis; cardiac arrest (CPR); severe bronchospasm",dosage:"Anaphylaxis: 0.01 mg/kg IV/IM; CPR: 0.01-0.1 mg/kg IV q3-5min",route:"IV; IM; intratracheal; IO",sideEffects:"Tachycardia; hypertension; tremors; anxiety; arrhythmias",warnings:"Ventricular arrhythmias; hypertensive crisis; tissue necrosis (extravasation)",interactions:"Beta-blockers (antagonized; may worsen hypertension); halothane/isoflurane (arrhythmia risk); alpha-blockers (hypotension)",foodInteractions:"N/A (injectable)",contraindications:"Caution in cardiac disease; concurrent halothane anesthesia",monitoring:"Continuous ECG; blood pressure; heart rate",notes:"1:1000 for IM (anaphylaxis); 1:10000 for IV (CPR); know the difference",alsoUsedIn:"Dogs; cats; all species"},
  {genericName:"Flumazenil",brandNames:"Romazicon",drugClass:"Benzodiazepine antagonist",indications:"Reversal of benzodiazepine sedation/overdose",dosage:"0.01-0.02 mg/kg IV slowly; repeat PRN",route:"IV",sideEffects:"Anxiety; agitation; seizures (if benzodiazepine was treating seizures)",warnings:"Seizure precipitation if reversing chronic benzodiazepine therapy; re-sedation (shorter half-life than most benzos)",interactions:"Specifically reverses benzodiazepines only",foodInteractions:"N/A (injectable)",contraindications:"Do NOT use if benzodiazepine is controlling active seizures",monitoring:"Sedation level; seizure risk; re-sedation monitoring",notes:"May need repeated doses (short half-life); monitor for re-sedation",alsoUsedIn:"Dogs; cats"},
  {genericName:"Phenylpropanolamine",brandNames:"Proin",drugClass:"Alpha-adrenergic agonist (urethral sphincter)",indications:"Urethral sphincter mechanism incompetence (USMI; urinary incontinence in spayed females)",dosage:"1-2 mg/kg PO q8-12h",route:"Oral",sideEffects:"Restlessness; hypertension; tachycardia; decreased appetite; irritability",warnings:"Hypertension; cardiac arrhythmias; stroke (rare)",interactions:"MAOIs (hypertensive crisis); other sympathomimetics; tricyclic antidepressants",foodInteractions:"Give with food",contraindications:"Hypertension; cardiac arrhythmias; glaucoma; diabetes; hyperthyroidism; concurrent MAOI",monitoring:"Blood pressure at 2wks then q6mo",notes:"Most common drug for canine urinary incontinence; FDA-approved (Proin)",alsoUsedIn:"Dogs primarily"},
  {genericName:"Allopurinol",brandNames:"Zyloprim",drugClass:"Xanthine oxidase inhibitor",indications:"Urate urolithiasis prevention; leishmaniasis adjunct",dosage:"10-15 mg/kg PO q12-24h",route:"Oral",sideEffects:"GI upset; xanthine urolithiasis (if high-purine diet continues)",warnings:"Xanthine stone formation (must restrict purines); hepatotoxicity (rare)",interactions:"Azathioprine (SEVERE toxicity; reduce azathioprine dose 25-33% or avoid); cyclophosphamide (myelosuppression); ampicillin (rash)",foodInteractions:"Give with food",contraindications:"Concurrent azathioprine (or reduce dose); must restrict dietary purines",monitoring:"Urinalysis; imaging for stones q6-12mo; liver values",notes:"MUST combine with low-purine diet to prevent xanthine stones",alsoUsedIn:"Dogs; cats (leishmaniasis)"},
  {genericName:"Cannabidiol (CBD)",brandNames:"Various veterinary products",drugClass:"Cannabinoid (non-psychoactive)",indications:"Osteoarthritis pain adjunct; seizure adjunct; anxiety (limited evidence)",dosage:"2-5 mg/kg PO q12h (evidence-based range for OA/seizures)",route:"Oral (oil; treats)",sideEffects:"Elevated liver enzymes; GI upset; sedation; diarrhea",warnings:"Hepatotoxicity (especially with concurrent phenobarbital/NSAIDs); drug interactions",interactions:"Phenobarbital (increased liver enzyme elevations); NSAIDs (liver); highly protein-bound drugs; CYP substrates",foodInteractions:"Give with food (increases absorption)",contraindications:"Severe hepatic disease; caution with concurrent hepatotoxic drugs",monitoring:"Liver values at 2wks then q3-6mo",notes:"Limited FDA-regulated products; quality varies widely; evidence strongest for OA and epilepsy adjunct",alsoUsedIn:"Dogs; cats (limited data)"},
  {genericName:"SAMe (S-adenosylmethionine)",brandNames:"Denosyl; Zentonil",drugClass:"Nutraceutical hepatoprotectant/antioxidant",indications:"Liver disease support; hepatoprotection during hepatotoxic drug therapy; cognitive dysfunction adjunct",dosage:"18-20 mg/kg PO q24h",route:"Oral (enteric-coated)",sideEffects:"GI upset (rare)",warnings:"None significant",interactions:"Minimal; often combined with other hepatoprotectants",foodInteractions:"Give on empty stomach (food reduces absorption by ~60%)",contraindications:"None",monitoring:"Liver values",notes:"Enteric coating must not be crushed; combine with silymarin/ursodiol for liver triad",alsoUsedIn:"Dogs; cats"},
  {genericName:"Silymarin (Milk Thistle)",brandNames:"Marin; various",drugClass:"Nutraceutical hepatoprotectant/antioxidant",indications:"Liver disease support; hepatoprotection; toxin ingestion adjunct",dosage:"5-10 mg/kg PO q24h (silymarin component; products vary widely)",route:"Oral",sideEffects:"GI upset (rare); loose stool",warnings:"None significant",interactions:"Minimal; may alter metabolism of some drugs (weak CYP effects)",foodInteractions:"Give with food",contraindications:"None",monitoring:"Liver values",notes:"Phosphatidylcholine-complexed forms (silybin) have better bioavailability",alsoUsedIn:"Dogs; cats"},
]
